# Generated by Django 6.0.6 on 2026-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Vacío = usa el nombre por defecto del deploy.', max_length=60)),
                ('logo_base64', models.TextField(blank=True)),
                ('logo_content_type', models.CharField(blank=True, max_length=40)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de marca',
                'verbose_name_plural': 'Configuración de marca',
            },
        ),
    ]
