# Generated by Django 6.0.6 on 2026-09-11 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('contacto_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('contacto_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, help_text='Saldo de la cuenta (wallet). Negativo = le facturamos; positivo = a favor del socio.', max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio comercial',
                'verbose_name_plural': 'Socios comerciales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entorno', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=4)),
                ('prefix', models.CharField(editable=False, max_length=24, unique=True)),
                ('secret_hash', models.CharField(editable=False, max_length=64)),
                ('activa', models.BooleanField(default=True)),
                ('ultimo_uso_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='partners.sociocomercial')),
            ],
            options={
                'verbose_name': 'Llave de API',
                'verbose_name_plural': 'Llaves de API',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('fallido', 'Fallido')], default='pendiente', max_length=10)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_codigo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='partners.sociocomercial')),
            ],
            options={
                'verbose_name': 'Entrega de webhook',
                'verbose_name_plural': 'Entregas de webhook',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('endpoint', models.CharField(max_length=120)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='partners.sociocomercial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('socio', 'key', 'endpoint'), name='idempotency_unica_por_socio_endpoint')],
            },
        ),
    ]
