# Generated by Django 6.0.6 on 2026-08-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_cliente_es_transportista'),
        ('servicios', '0006_servicio_autoriza_compartir_fotos_transportistas_and_more'),
        ('whatsapp', '0025_conversacionwhatsapp_archivada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaTransportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ofertado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_transportista', to='clientes.cliente')),
                ('mensaje_origen', models.ForeignKey(blank=True, help_text='Mensaje donde el transportista declaró el precio — evidencia/trazabilidad, no se duplica el texto aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.mensajewhatsapp')),
            ],
            options={
                'verbose_name': 'Oferta de transportista',
                'verbose_name_plural': 'Ofertas de transportistas',
                'ordering': ['precio_ofertado', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('texto_publicado', models.TextField(help_text='Snapshot del texto generado al momento de publicar. No garantiza que sea lo pegado tal cual — el asesor puede editarlo antes de pegarlo en el grupo.')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('adjudicada', 'Adjudicada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('grupos_publicados', models.JSONField(blank=True, default=list, help_text='Nombres de grupos donde el asesor marcó que pegó la publicación. Autoreportado, no verificable por la API.')),
                ('adjudicada_en', models.DateTimeField(blank=True, null=True)),
                ('adjudicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_tercerizacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('oferta_ganadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tercerizacion.ofertatransportista')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_tercerizacion', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Publicación de carga',
                'verbose_name_plural': 'Publicaciones de carga',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='ofertatransportista',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='tercerizacion.publicacioncarga'),
        ),
        migrations.AddConstraint(
            model_name='ofertatransportista',
            constraint=models.UniqueConstraint(fields=('publicacion', 'cliente'), name='una_oferta_por_transportista_por_publicacion'),
        ),
    ]
