# Generated by Django 6.0.6 on 2026-08-30 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0001_initial'),
        ('whatsapp', '0025_conversacionwhatsapp_archivada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportistaBotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(choices=[('esperando_codigo', 'Esperando código'), ('esperando_intencion', 'Esperando ofertar/consultar'), ('recogiendo_precio', 'Recogiendo precio'), ('conversando', 'Conversando')], default='esperando_codigo', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conversacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_bot_transportista', to='whatsapp.conversacionwhatsapp')),
                ('publicacion_activa', models.ForeignKey(blank=True, help_text='Sobre qué OFERTA-<código> versa la conversación ahora mismo. NULL = todavía no se identificó ninguna (o se perdió el contexto) — en ese estado el bot nunca responde, cede al asesor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tercerizacion.publicacioncarga')),
            ],
            options={
                'verbose_name': 'Estado del bot de transportistas',
                'verbose_name_plural': 'Estados del bot de transportistas',
            },
        ),
    ]
