# Generated by Django 6.0.6 on 2026-08-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0002_transportistabotstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportistabotstate',
            name='pausado',
            field=models.BooleanField(default=False, help_text='Silencia el bot SOLO para esta conversación — override manual del asesor, independiente del interruptor global de transportistas y del pausado general del sistema.'),
        ),
    ]
