# Generated by Django 6.0.6 on 2026-09-07 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0008_cliente_es_campo'),
        ('tercerizacion', '0003_transportistabotstate_pausado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Razón social o nombre', max_length=160)),
                ('documento', models.CharField(blank=True, help_text='RUC o DNI', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_conductor', models.BooleanField(default=False, help_text='El transportista también maneja sus vehículos.')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Contacto de WhatsApp asociado, si existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportistas_afiliados', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transportista afiliado',
                'verbose_name_plural': 'Transportistas afiliados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TransportistaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('capacidad_util_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Capacidad útil (ton)')),
                ('largo_util_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largo útil (m)')),
                ('ancho_util_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ancho útil (m)')),
                ('alto_util_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alto útil (m)')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Se asigna automáticamente según la capacidad útil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogo.categoriavehiculo')),
                ('tipo_carroceria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogo.tipocarroceria')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.tipovehiculo')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='tercerizacion.transportista')),
            ],
            options={
                'verbose_name': 'Vehículo de transportista',
                'verbose_name_plural': 'Vehículos de transportistas',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='TransportistaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('numero_licencia', models.CharField(blank=True, max_length=40, verbose_name='N° Licencia')),
                ('categoria_licencia', models.CharField(blank=True, choices=[('A-I', 'A-I'), ('A-II-a', 'A-II-a'), ('A-II-b', 'A-II-b'), ('A-III-a', 'A-III-a'), ('A-III-b', 'A-III-b'), ('A-III-c', 'A-III-c'), ('B-I', 'B-I'), ('B-II-a', 'B-II-a'), ('B-II-b', 'B-II-b'), ('B-II-c', 'B-II-c')], max_length=20, verbose_name='Categoría')),
                ('fecha_vencimiento_licencia', models.DateField(blank=True, null=True, verbose_name='Vencimiento Licencia')),
                ('es_titular', models.BooleanField(default=False, help_text='Es el propio transportista.')),
                ('activo', models.BooleanField(default=True)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='tercerizacion.transportista')),
            ],
            options={
                'verbose_name': 'Conductor de transportista',
                'verbose_name_plural': 'Conductores de transportistas',
                'constraints': [models.UniqueConstraint(fields=('transportista', 'dni'), name='tercerizacion_conductor_dni_por_transportista')],
            },
        ),
    ]
