# Generated by Django 6.0.6 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0004_transportista_transportistavehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatransportista',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, help_text="Cuándo el transportista aceptó (FIFO para adjudicación 'primero que acepta').", null=True),
        ),
        migrations.AddField(
            model_name='ofertatransportista',
            name='monto_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Último monto vigente de la negociación (contraofertas).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='alcance',
            field=models.CharField(choices=[('todos', 'Todos los transportistas'), ('red_confianza', 'Red de confianza'), ('seleccion', 'Selección')], default='todos', max_length=16),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='criterio_adjudicacion',
            field=models.CharField(choices=[('primero_acepta', 'Primero que acepta'), ('cercania_compat', 'Cercanía + compatibilidad (futuro)')], default='primero_acepta', max_length=16),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='modo_precio',
            field=models.CharField(choices=[('fijo', 'Precio fijo'), ('referencial', 'Precio referencial'), ('abierto', 'Abierto (a proponer)')], default='abierto', max_length=12),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='precio_publicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo objetivo hacia el transportista (no el precio de venta al cliente).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='vigencia_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofertatransportista',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('contraoferta_taxicarga', 'Contraoferta de TaxiCarga'), ('contraoferta_transportista', 'Contraoferta del transportista'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada'), ('vencida', 'Vencida')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='ofertatransportista',
            name='precio_ofertado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Primer precio que puso el transportista (se conserva).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicacioncarga',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('publicada', 'Publicada'), ('con_ofertas', 'Con ofertas'), ('adjudicada', 'Adjudicada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='abierta', max_length=20),
        ),
    ]
