# Generated by Django 6.0.6 on 2026-09-09 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_tipo'),
        ('cotizador', '0013_cotizacion_confianza_cotizacion_modo_and_more'),
        ('leads', '0017_lead_categoria_carga_lead_codigo_and_more'),
        ('tercerizacion', '0005_ofertatransportista_fecha_aceptacion_and_more'),
        ('whatsapp', '0029_alter_respuestarapida_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiloNegociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta (cliente)'), ('compra', 'Compra (transportista)')], max_length=8)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('pausada', 'Pausada'), ('acuerdo', 'Con acuerdo'), ('sin_acuerdo', 'Sin acuerdo'), ('cerrada', 'Cerrada')], default='abierta', max_length=12)),
                ('monto_objetivo', models.DecimalField(blank=True, decimal_places=2, help_text='Venta: precio de venta que busca TaxiCarga. Compra: costo tope.', max_digits=10, null=True)),
                ('monto_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Última propuesta viva sobre la mesa.', max_digits=10, null=True)),
                ('monto_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo_pausa', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('contraparte', models.ForeignKey(blank=True, help_text='El cliente (venta) o el transportista (compra) con quien se negocia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_negociacion', to='clientes.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_negociacion', to='cotizador.cotizacioncomercial')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hilos_negociacion', to='leads.lead')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_negociacion', to='tercerizacion.publicacioncarga')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Asesor que controla el hilo (queda al pausar).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hilo de negociación',
                'verbose_name_plural': 'Hilos de negociación',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeNegociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('cliente', 'Cliente'), ('taxicarga', 'TaxiCarga'), ('transportista', 'Transportista'), ('sistema', 'Sistema')], max_length=14)),
                ('canal', models.CharField(choices=[('crm', 'CRM'), ('portal', 'Portal'), ('whatsapp', 'WhatsApp')], default='crm', max_length=10)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('propuesta', 'Propuesta'), ('sistema', 'Sistema')], default='texto', max_length=10)),
                ('texto', models.TextField(blank=True)),
                ('propuesta_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('propuesta_estado', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('contraofertada', 'Contraofertada'), ('rechazada', 'Rechazada')], max_length=14)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, help_text='Usuario del CRM que tipeó el mensaje, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tercerizacion.hilonegociacion')),
                ('mensaje_whatsapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.mensajewhatsapp')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de negociación',
                'verbose_name_plural': 'Mensajes de negociación',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='hilonegociacion',
            constraint=models.UniqueConstraint(condition=models.Q(('contraparte__isnull', False)), fields=('lead', 'tipo', 'contraparte'), name='hilo_unico_por_lead_tipo_contraparte'),
        ),
    ]
