# Generated by Django 6.0.6 on 2026-09-09 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_tipo'),
        ('cotizador', '0013_cotizacion_confianza_cotizacion_modo_and_more'),
        ('leads', '0017_lead_categoria_carga_lead_codigo_and_more'),
        ('tercerizacion', '0006_hilonegociacion_mensajenegociacion_and_more'),
        ('whatsapp', '0029_alter_respuestarapida_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ofertatransportista',
            name='una_oferta_por_transportista_por_publicacion',
        ),
        migrations.AddField(
            model_name='hilonegociacion',
            name='transportista',
            field=models.ForeignKey(blank=True, help_text='Compra: el transportista afiliado con quien se negocia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hilos_negociacion', to='tercerizacion.transportista'),
        ),
        migrations.AddField(
            model_name='ofertatransportista',
            name='transportista',
            field=models.ForeignKey(blank=True, help_text='Transportista afiliado (canal crm/portal, y necesario para adjudicar).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='tercerizacion.transportista'),
        ),
        migrations.AddField(
            model_name='ofertatransportista',
            name='transportista_vehiculo',
            field=models.ForeignKey(blank=True, help_text='Vehículo con el que cubriría el servicio (se fija al adjudicar).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tercerizacion.transportistavehiculo'),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='publicada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='publicada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hilonegociacion',
            name='contraparte',
            field=models.ForeignKey(blank=True, help_text='Venta: el cliente. Compra: el contacto de WhatsApp del transportista (si lo hay).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_negociacion', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ofertatransportista',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Contacto de WhatsApp que ofertó (canal whatsapp). NULL si la ofertó el asesor por CRM/portal a nombre de un afiliado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_transportista', to='clientes.cliente'),
        ),
        migrations.AddConstraint(
            model_name='hilonegociacion',
            constraint=models.UniqueConstraint(condition=models.Q(('transportista__isnull', False)), fields=('lead', 'tipo', 'transportista'), name='hilo_compra_unico_por_afiliado'),
        ),
        migrations.AddConstraint(
            model_name='ofertatransportista',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente__isnull', False)), fields=('publicacion', 'cliente'), name='una_oferta_por_transportista_por_publicacion'),
        ),
        migrations.AddConstraint(
            model_name='ofertatransportista',
            constraint=models.UniqueConstraint(condition=models.Q(('transportista__isnull', False)), fields=('publicacion', 'transportista'), name='una_oferta_por_afiliado_por_publicacion'),
        ),
    ]
