# Generated by Django 6.0.6 on 2026-09-09 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0007_remove_ofertatransportista_una_oferta_por_transportista_por_publicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text="Cuenta de acceso al Portal del Transportista (grupo 'Transportista').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportista_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
