# Generated by Django 6.0.6 on 2026-09-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0008_transportista_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, default='', help_text='Categoría de carga a la que aplica este tramo. Vacío = tabla general (aplica a cualquier categoría sin tabla propia).', max_length=20)),
                ('monto_desde', models.DecimalField(decimal_places=2, default=0, help_text='Precio del servicio desde el cual aplica este porcentaje (inclusive).', max_digits=10)),
                ('monto_hasta', models.DecimalField(blank=True, decimal_places=2, help_text='Hasta (exclusivo). Vacío = sin tope (de este monto para arriba).', max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Comisión de la plataforma sobre el precio del servicio, en %.', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tramo de comisión',
                'verbose_name_plural': 'Tabla de comisiones',
                'ordering': ['categoria', 'monto_desde'],
            },
        ),
    ]
