# Generated by Django 6.0.6 on 2026-09-10 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0008_filapizarratransportista_and_more'),
        ('servicios', '0013_configuracionoperaciones_monto_minimo_comisionable_and_more'),
        ('tercerizacion', '0009_tramocomision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_servicio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_transportista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comision_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sin_comision', models.BooleanField(default=False)),
                ('exencion_motivo', models.CharField(blank=True, default='', max_length=200)),
                ('medio_cobro_cliente', models.CharField(choices=[('por_definir', 'Por definir'), ('pasarela', 'Pasarela (el cliente pagó a la plataforma)'), ('transferencia', 'Transferencia a la plataforma'), ('efectivo_transportista', 'Efectivo cobrado por el transportista')], default='por_definir', max_length=24)),
                ('neto', models.DecimalField(decimal_places=2, default=0, help_text='Positivo: la plataforma paga al transportista. Negativo: el transportista debe a la plataforma.', max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conciliada', 'Conciliada (lista para liquidar)'), ('pagada', 'Liquidada'), ('anulada', 'Anulada')], default='pendiente', max_length=12)),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('referencia_pago', models.CharField(blank=True, default='', max_length=120)),
                ('comprobante', models.CharField(blank=True, default='', max_length=255)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('liquidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='campo.programacionservicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='servicios.servicio')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='tercerizacion.transportista')),
            ],
            options={
                'verbose_name': 'Liquidación de tercerización',
                'verbose_name_plural': 'Liquidaciones de tercerización',
                'ordering': ['-creado_en'],
            },
        ),
    ]
