# Generated by Django 6.0.6 on 2026-09-10 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0010_liquidacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='pago_banco',
            field=models.CharField(blank=True, choices=[('bcp', 'BCP'), ('bbva', 'BBVA'), ('interbank', 'Interbank'), ('scotiabank', 'Scotiabank'), ('nacion', 'Banco de la Nación'), ('otro', 'Otro')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='transportista',
            name='pago_cci',
            field=models.CharField(blank=True, default='', help_text='Código de Cuenta Interbancario (20 dígitos) — para transferencias entre bancos.', max_length=20),
        ),
        migrations.AddField(
            model_name='transportista',
            name='pago_numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='transportista',
            name='pago_tipo_cuenta',
            field=models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transportista',
            name='pago_titular',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='transportista',
            name='pago_yape',
            field=models.CharField(blank=True, default='', help_text='Número Yape / Plin.', max_length=20),
        ),
        migrations.CreateModel(
            name='LotePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='borrador', max_length=10)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('yape', 'Yape / Plin'), ('otro', 'Otro')], default='transferencia', max_length=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de pago a transportistas',
                'verbose_name_plural': 'Lotes de pago a transportistas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='tercerizacion.lotepago'),
        ),
    ]
