# Generated by Django 6.0.6 on 2026-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0011_transportista_pago_banco_transportista_pago_cci_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaCargaParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, default='', help_text="Ciudad o región de destino (p. ej. 'Arequipa'). Vacío = tarifa general (aplica a cualquier destino sin tabla propia).", max_length=120)),
                ('peso_desde_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso de la carga desde el cual aplica este tramo (inclusive), en kg.', max_digits=8)),
                ('peso_hasta_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Hasta (exclusivo), en kg. Vacío = sin tope (de este peso para arriba).', max_digits=8, null=True)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, help_text='Precio al cliente por kg dentro de este tramo (soles).', max_digits=8)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Precio mínimo a cobrar en este tramo, aunque el peso × precio_por_kg sea menor (piso para cargas chicas).', max_digits=10)),
                ('dias_estimados', models.PositiveSmallIntegerField(default=5, help_text='Plazo de entrega estimado (días hábiles) para este tramo.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa de carga parcial',
                'verbose_name_plural': 'Tabla de tarifas de carga parcial',
                'ordering': ['destino', 'peso_desde_kg'],
            },
        ),
    ]
