# Generated by Django 6.0.6 on 2026-09-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0012_tarifacargaparcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transportista',
            name='lat_frecuente',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='transportista',
            name='lng_frecuente',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='transportista',
            name='ubicacion_frecuente',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Distrito (Lima) o ciudad donde opera habitualmente. Se usa para encontrar afiliados en la ciudad destino de una encomienda interprovincial.', max_length=120),
        ),
    ]
