# Generated by Django 6.0.6 on 2026-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0013_transportista_direccion_transportista_lat_frecuente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportistavehiculo',
            name='foto_1',
            field=models.FileField(blank=True, null=True, upload_to='transportistas/vehiculos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transportistavehiculo',
            name='foto_2',
            field=models.FileField(blank=True, null=True, upload_to='transportistas/vehiculos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transportistavehiculo',
            name='foto_3',
            field=models.FileField(blank=True, null=True, upload_to='transportistas/vehiculos/%Y/%m/'),
        ),
    ]
