# Generated by Django 6.0.6 on 2026-09-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0014_transportistavehiculo_foto_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatransportista',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('completa', 'Completa (camión dedicado)'), ('parcial', 'Parcial (consolidada con otra carga del transportista)')], default='', help_text='Solo tiene sentido si la publicación es de una carga interprovincial (completa/Express = camión dedicado, parcial/Consolidada = comparte camión con otra carga). La declara el transportista al ofertar — él es quien sabe si dedica el camión o va con carga propia compartida. Vacío = no aplica (carga local) o no se declaró.', max_length=10),
        ),
    ]
