# Generated by Django 6.0.6 on 2026-09-20 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0015_ofertatransportista_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioncarga',
            name='oferta_preferida_cliente',
            field=models.ForeignKey(blank=True, help_text='Oferta que el cliente marcó como preferida. Vacío si prefiere el precio directo (ver prefiere_directo_taxicarga) o todavía no eligió.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferida_por_cliente_en', to='tercerizacion.ofertatransportista'),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='preferencia_cliente_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacioncarga',
            name='prefiere_directo_taxicarga',
            field=models.BooleanField(default=False, help_text='El cliente prefirió el precio directo de TaxiCarga en vez de una oferta de transportista (no es una OfertaTransportista real, ver client_offer_item).'),
        ),
    ]
