# Generated by Django 6.0.6 on 2026-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0016_publicacioncarga_oferta_preferida_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifacargaparcial',
            options={'ordering': ['modalidad', 'destino', 'peso_desde_kg'], 'verbose_name': 'Tarifa de carga nacional', 'verbose_name_plural': 'Tabla de tarifas de carga nacional'},
        ),
        migrations.AddField(
            model_name='tarifacargaparcial',
            name='modalidad',
            field=models.CharField(choices=[('completa', 'Completa (camión dedicado)'), ('parcial', 'Parcial (consolidada con otra carga del transportista)')], default='parcial', help_text='Completa (camión dedicado) o Parcial (comparte camión) — cada una con su propia tabla.', max_length=10),
        ),
        migrations.AddField(
            model_name='tarifacargaparcial',
            name='precio_por_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio al cliente por m³ dentro de este tramo (soles) — 'peso volumétrico': se cobra el que salga más caro entre peso×precio_por_kg y volumen×precio_por_m3. Vacío = no se cobra por volumen, solo por peso.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tarifacargaparcial',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio mínimo a cobrar en este tramo, aunque peso/volumen den menos (piso para cargas chicas).', max_digits=10),
        ),
    ]
