# Generated by Django 6.0.6 on 2026-09-23 21:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0017_alter_tarifacargaparcial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="P. ej. 'Lima - Ica - Tacna'.", max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('origen_nombre', models.CharField(blank=True, default='Lima', max_length=120)),
                ('origen_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origen_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destino_nombre', models.CharField(blank=True, max_length=120)),
                ('destino_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destino_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('trazado', models.JSONField(blank=True, default=list, help_text='Lista [[lng,lat], ...] de la ruta real (formato GeoJSON, mismo orden que devuelve Mapbox Directions) — la guarda el frontend, el backend solo la persiste y la recorre. Vacía = todavía no se calculó (el matcheo por radio de parada funciona igual sin ella).')),
                ('tolerancia_eje_km', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Cuán lejos del EJE de la carretera (no de una ciudad) puede caer un punto para seguir considerándose 'sobre la ruta' y ofrecerle Compartida.", max_digits=5)),
                ('desvio_maximo_km', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text="Más allá de esta distancia al eje, el punto ya no tiene nada que ver con este corredor (ni siquiera como desvío tipo Lunahuaná) — solo Exclusivo. Sin este tope, cualquier punto del Perú terminaría 'matcheando' al corredor geométricamente más cercano.", max_digits=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corredor de carga nacional',
                'verbose_name_plural': 'Corredores de carga nacional',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CorredorParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Debe coincidir con TarifaCargaParcial.destino.', max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Solo UI (lista ordenable), no autoritativo.')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radio_km', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Radio de cobertura de Compartida alrededor del centro de esta ciudad.', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='tercerizacion.corredor')),
            ],
            options={
                'verbose_name': 'Parada de corredor',
                'verbose_name_plural': 'Paradas de corredor',
                'ordering': ['corredor', 'orden'],
                'unique_together': {('corredor', 'nombre'), ('corredor', 'orden')},
            },
        ),
    ]
