# Generated by Django 6.0.6 on 2026-09-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0019_seed_corredores_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramoVial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometria', models.JSONField(blank=True, default=list, help_text='[[lng,lat], ...] en el sentido nodo_inicio→nodo_fin, tal como lo devuelve Mapbox Directions.')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('codigo_carretera', models.CharField(blank=True, default='', help_text="P. ej. 'PE-1N'.", max_length=20)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE_TRAZADO', 'Pendiente'), ('TRAZADO_CALCULADO', 'Calculado'), ('ERROR_TRAZADO', 'Error')], default='PENDIENTE_TRAZADO', max_length=20)),
                ('fuente_geografica', models.CharField(blank=True, default='', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tramo vial',
                'verbose_name_plural': 'Tramos viales',
            },
        ),
        migrations.AddField(
            model_name='corredor',
            name='codigo',
            field=models.CharField(blank=True, default='', help_text="Identificador interno estable (p. ej. 'N05'). Vacío en corredores cargados a mano antes del catálogo de 40.", max_length=20),
        ),
        migrations.AddField(
            model_name='corredor',
            name='distancia_total_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cacheada, recalculada junto con `trazado` cuando hay tramos.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE_TRAZADO', 'Pendiente de trazado'), ('TRAZADO_CALCULADO', 'Trazado calculado'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('VALIDADO', 'Validado'), ('ERROR_TRAZADO', 'Error de trazado'), ('INACTIVO', 'Inactivo')], default='PENDIENTE_TRAZADO', help_text='Estado de la GEOMETRÍA (independiente de `activo`, que es la habilitación comercial). Solo VALIDADO significa que un humano revisó y aprobó el trazado calculado — nunca se auto-promueve.', max_length=24),
        ),
        migrations.AddField(
            model_name='corredor',
            name='modificado_manualmente',
            field=models.BooleanField(default=False, help_text='True en cuanto un admin edita este corredor desde el CRUD — el seed/backfill de los 40 corredores nunca vuelve a tocar sus campos.'),
        ),
        migrations.AddField(
            model_name='corredor',
            name='variante',
            field=models.CharField(blank=True, default='', help_text="P. ej. 'vía Norte' / 'vía Centro' — dos corredores con el mismo origen/destino pero recorridos distintos NUNCA se fusionan.", max_length=60),
        ),
        migrations.AddField(
            model_name='corredorparada',
            name='distancia_acceso_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia real de acarreo si la parada está fuera del eje del corredor.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='corredorparada',
            name='modificado_manualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corredorparada',
            name='punto_acceso_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='corredorparada',
            name='punto_acceso_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='corredorparada',
            name='requiere_desvio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corredorparada',
            name='tipo_parada',
            field=models.CharField(blank=True, choices=[('ciudad_principal', 'Ciudad principal'), ('ciudad_intermedia', 'Ciudad intermedia'), ('pueblo', 'Pueblo / centro poblado'), ('cruce_vial', 'Cruce o desvío vial')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='trazado',
            field=models.JSONField(blank=True, default=list, help_text="Lista [[lng,lat], ...] de la ruta real (formato GeoJSON, mismo orden que devuelve Mapbox Directions). Se puede cargar a mano desde el frontend (botón 'Calcular trazado') O derivarse automáticamente concatenando la geometría de sus `tramos` (ver apps.tercerizacion.corredores.recalcular_trazado) cuando el corredor tiene CorredorTramo asociados — en ese caso el campo pasa a ser de solo lectura desde la API. Vacía = todavía no se calculó (el matcheo por radio de parada funciona igual sin ella)."),
        ),
        migrations.CreateModel(
            name='CorredorTramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('sentido', models.CharField(choices=[('ida', 'nodo_inicio → nodo_fin'), ('vuelta', 'nodo_fin → nodo_inicio')], default='ida', max_length=10)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='tercerizacion.corredor')),
            ],
            options={
                'verbose_name': 'Tramo de corredor',
                'verbose_name_plural': 'Tramos de corredor',
                'ordering': ['corredor', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(db_index=True, editable=False, max_length=120)),
                ('departamento', models.CharField(blank=True, default='', max_length=60)),
                ('provincia', models.CharField(blank=True, default='', max_length=60)),
                ('distrito', models.CharField(blank=True, default='', max_length=60)),
                ('ubigeo', models.CharField(blank=True, default='', max_length=6)),
                ('tipo', models.CharField(choices=[('ciudad_principal', 'Ciudad principal'), ('ciudad_intermedia', 'Ciudad intermedia'), ('pueblo', 'Pueblo / centro poblado'), ('cruce_vial', 'Cruce o desvío vial')], default='ciudad_intermedia', max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radio_atencion_km', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = usa el default de RADIO_DEFAULT_KM según `tipo` (ver radio_efectivo_km()).', max_digits=5, null=True)),
                ('fuente_geografica', models.CharField(blank=True, default='', help_text="'geonames' | 'manual' | '' (todavía sin geocodificar).", max_length=20)),
                ('geonames_id', models.CharField(blank=True, default='', max_length=20)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE_TRAZADO', 'Sin geocodificar'), ('RESUELTO', 'Resuelto'), ('AMBIGUO', 'Ambiguo — requiere revisión manual')], default='PENDIENTE_TRAZADO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('modificado_manualmente', models.BooleanField(default=False, help_text='El seed/geocodificador nunca vuelve a tocar una fila con esto en True.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre_normalizado', 'departamento'), name='localidad_nombre_depto_unico')],
            },
        ),
        migrations.AddField(
            model_name='corredor',
            name='localidad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corredores_como_destino', to='tercerizacion.localidad'),
        ),
        migrations.AddField(
            model_name='corredor',
            name='localidad_origen',
            field=models.ForeignKey(blank=True, help_text='Nullable a propósito: corredores cargados a mano (antes del catálogo de 40) siguen mostrando origen_nombre sin tener esta FK.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corredores_como_origen', to='tercerizacion.localidad'),
        ),
        migrations.AddField(
            model_name='corredorparada',
            name='localidad',
            field=models.ForeignKey(blank=True, help_text='Referencia al grafo de corredores compartidos — `nombre` (arriba) sigue siendo el campo que matchea contra TarifaCargaParcial.destino para el precio, esta FK es solo para el grafo, no lo reemplaza.', null=True, on_delete=django.db.models.deletion.PROTECT, to='tercerizacion.localidad'),
        ),
        migrations.AddConstraint(
            model_name='corredor',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__gt', '')), fields=('codigo',), name='corredor_codigo_unico'),
        ),
        migrations.AddField(
            model_name='tramovial',
            name='nodo_fin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramos_como_fin', to='tercerizacion.localidad'),
        ),
        migrations.AddField(
            model_name='tramovial',
            name='nodo_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramos_como_inicio', to='tercerizacion.localidad'),
        ),
        migrations.AddField(
            model_name='corredortramo',
            name='tramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corredores', to='tercerizacion.tramovial'),
        ),
        migrations.AddConstraint(
            model_name='tramovial',
            constraint=models.UniqueConstraint(fields=('nodo_inicio', 'nodo_fin'), name='tramo_par_nodos_unico'),
        ),
        migrations.AddConstraint(
            model_name='corredortramo',
            constraint=models.UniqueConstraint(fields=('corredor', 'orden'), name='corredortramo_orden_unico'),
        ),
    ]
