# Generated by Django 6.0.6 on 2026-09-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizacion', '0020_tramovial_corredor_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifacargaparcial',
            name='precio_por_kg_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por kg — extremo MÁXIMO del rango. Vacío = sin rango, se cobra un solo precio (precio_por_kg) como antes.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tarifacargaparcial',
            name='precio_por_m3_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extremo MÁXIMO del precio por m³ — mismo criterio que precio_por_kg_max.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tarifacargaparcial',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, help_text='Precio por kg — extremo MÍNIMO del rango (o el único precio si no se carga un máximo).', max_digits=8),
        ),
    ]
