# Generated by Django 6.0.6 on 2026-08-08 05:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_correo_cliente_documento_and_more'),
        ('whatsapp', '0011_configuracionbot_asesor_predeterminado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatwootAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=40)),
                ('account_id', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('environment', 'account_id'), name='int_cw_account_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ChannelInboxMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_id', models.CharField(max_length=80)),
                ('inbox_identifier', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_mappings', to='whatsapp.whatsappchannel')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='integrations.chatwootaccountmapping')),
            ],
        ),
        migrations.CreateModel(
            name='AgentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatwoot_user_id', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.chatwootaccountmapping')),
            ],
        ),
        migrations.CreateModel(
            name='ChatwootContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=80)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.chatwootaccountmapping')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_mappings', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInboxMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=160)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_sources', to='integrations.chatwootcontactmapping')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_sources', to='integrations.channelinboxmapping')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_state', models.CharField(choices=[('BOT_ACTIVO', 'Bot activo'), ('ESPERANDO_ASESOR', 'Esperando asesor'), ('ASESOR_ACTIVO', 'Asesor activo'), ('DEVOLVIENDO_AL_BOT', 'Devolviendo al bot'), ('CERRADA', 'Cerrada')], default='BOT_ACTIVO', max_length=24)),
                ('control_version', models.PositiveBigIntegerField(default=0)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reason', models.CharField(blank=True, max_length=120)),
                ('last_actor_type', models.CharField(blank=True, max_length=30)),
                ('last_correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_controls', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_control', to='whatsapp.conversacionwhatsapp')),
                ('last_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_control_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_conversation_id', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('contact_inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.contactinboxmapping')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_mappings', to='whatsapp.conversacionwhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTransitionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(choices=[('BOT_ACTIVO', 'Bot activo'), ('ESPERANDO_ASESOR', 'Esperando asesor'), ('ASESOR_ACTIVO', 'Asesor activo'), ('DEVOLVIENDO_AL_BOT', 'Devolviendo al bot'), ('CERRADA', 'Cerrada')], max_length=24)),
                ('to_state', models.CharField(choices=[('BOT_ACTIVO', 'Bot activo'), ('ESPERANDO_ASESOR', 'Esperando asesor'), ('ASESOR_ACTIVO', 'Asesor activo'), ('DEVOLVIENDO_AL_BOT', 'Devolviendo al bot'), ('CERRADA', 'Cerrada')], max_length=24)),
                ('action', models.CharField(max_length=50)),
                ('actor_type', models.CharField(default='system', max_length=30)),
                ('external_actor_ref', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('version_before', models.PositiveBigIntegerField()),
                ('version_after', models.PositiveBigIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_audits', to='whatsapp.conversacionwhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationInboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('meta_whatsapp', 'Meta WhatsApp'), ('chatwoot', 'Chatwoot'), ('internal', 'Interno'), ('meta_messenger', 'Meta Messenger'), ('meta_instagram', 'Meta Instagram'), ('email', 'Correo'), ('webchat', 'Chat web'), ('web_form', 'Formulario web')], max_length=30)),
                ('external_event_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('safe_payload', models.JSONField(blank=True, default=dict)),
                ('account_ref', models.CharField(blank=True, max_length=120)),
                ('inbox_ref', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('ignored', 'Ignorado'), ('retry', 'Reintento'), ('dead_letter', 'Fallo definitivo'), ('quarantined', 'Cuarentena')], default='received', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.whatsappchannel')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.conversacionwhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('meta_whatsapp', 'Meta WhatsApp'), ('chatwoot', 'Chatwoot'), ('internal', 'Interno'), ('meta_messenger', 'Meta Messenger'), ('meta_instagram', 'Meta Instagram'), ('email', 'Correo'), ('webchat', 'Chat web'), ('web_form', 'Formulario web')], max_length=30)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente'), ('internal', 'Interno')], max_length=12)),
                ('author_type', models.CharField(choices=[('customer', 'Cliente'), ('bot', 'Bot'), ('agent', 'Asesor'), ('external_human', 'Humano externo'), ('system', 'Sistema'), ('unknown', 'Desconocido')], max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='private', max_length=10)),
                ('content_type', models.CharField(default='text', max_length=30)),
                ('text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('external_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_messages', to='whatsapp.conversacionwhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalMessageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta_whatsapp', 'Meta WhatsApp'), ('chatwoot', 'Chatwoot'), ('internal', 'Interno'), ('meta_messenger', 'Meta Messenger'), ('meta_instagram', 'Meta Instagram'), ('email', 'Correo'), ('webchat', 'Chat web'), ('web_form', 'Formulario web')], max_length=30)),
                ('account_scope', models.CharField(blank=True, max_length=120)),
                ('external_id', models.CharField(max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.mensajewhatsapp')),
                ('logical_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integrationmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ContextCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_version', models.PositiveBigIntegerField()),
                ('history_scope', models.JSONField(blank=True, default=dict)),
                ('advisor_instruction', models.TextField(blank=True)),
                ('resume_mode', models.CharField(choices=[('wait_for_customer', 'Esperar cliente'), ('respond_now', 'Responder ahora')], default='wait_for_customer', max_length=20)),
                ('collected_data', models.JSONField(blank=True, default=dict)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('rebuilding', 'Reconstruyendo'), ('ready', 'Listo'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_checkpoints', to='whatsapp.conversacionwhatsapp')),
                ('last_public_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integrationmessage')),
            ],
        ),
        migrations.CreateModel(
            name='BotGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_version_started', models.PositiveBigIntegerField()),
                ('expected_owner_state', models.CharField(choices=[('BOT_ACTIVO', 'Bot activo'), ('ESPERANDO_ASESOR', 'Esperando asesor'), ('ASESOR_ACTIVO', 'Asesor activo'), ('DEVOLVIENDO_AL_BOT', 'Devolviendo al bot'), ('CERRADA', 'Cerrada')], default='BOT_ACTIVO', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('ready', 'Lista'), ('published', 'Publicada'), ('cancelled', 'Cancelada'), ('failed', 'Fallida')], default='pending', max_length=15)),
                ('request_key', models.CharField(max_length=255)),
                ('result_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=120)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_generations', to='whatsapp.conversacionwhatsapp')),
                ('input_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='integrations.integrationmessage')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta_whatsapp', 'Meta WhatsApp'), ('chatwoot', 'Chatwoot'), ('internal', 'Interno'), ('meta_messenger', 'Meta Messenger'), ('meta_instagram', 'Meta Instagram'), ('email', 'Correo'), ('webchat', 'Chat web'), ('web_form', 'Formulario web')], max_length=30)),
                ('external_attachment_id', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('error', 'Error'), ('stale', 'Desactualizado'), ('archived', 'Archivado')], default='pending', max_length=15)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.evidenciawhatsapp')),
                ('logical_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integrationmessage')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(choices=[('meta_whatsapp', 'Meta WhatsApp'), ('chatwoot', 'Chatwoot'), ('internal', 'Interno'), ('meta_messenger', 'Meta Messenger'), ('meta_instagram', 'Meta Instagram'), ('email', 'Correo'), ('webchat', 'Chat web'), ('web_form', 'Formulario web')], max_length=30)),
                ('event_type', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('safe_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('retry', 'Reintento'), ('dead_letter', 'Fallo definitivo'), ('cancelled', 'Cancelado'), ('reconciled', 'Conciliado')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=8)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.conversacionwhatsapp')),
                ('logical_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to='integrations.integrationmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='channelinboxmapping',
            constraint=models.UniqueConstraint(fields=('account', 'inbox_id'), name='int_cw_inbox_uniq'),
        ),
        migrations.AddConstraint(
            model_name='channelinboxmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('channel',), name='int_channel_active_inbox_uniq'),
        ),
        migrations.AddConstraint(
            model_name='agentmapping',
            constraint=models.UniqueConstraint(fields=('account', 'chatwoot_user_id'), name='int_cw_agent_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chatwootcontactmapping',
            constraint=models.UniqueConstraint(fields=('account', 'contact_id'), name='int_cw_contact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='contactinboxmapping',
            constraint=models.UniqueConstraint(fields=('inbox', 'source_id'), name='int_cw_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='contactinboxmapping',
            constraint=models.UniqueConstraint(fields=('contact', 'inbox'), name='int_cw_contact_inbox_uniq'),
        ),
        migrations.AddIndex(
            model_name='conversationcontrol',
            index=models.Index(fields=['owner_state', 'updated_at'], name='int_ctrl_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmapping',
            constraint=models.UniqueConstraint(fields=('contact_inbox', 'external_conversation_id'), name='int_cw_conversation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversationmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('conversation',), name='int_local_active_conv_map_uniq'),
        ),
        migrations.AddIndex(
            model_name='conversationtransitionaudit',
            index=models.Index(fields=['conversation', 'created_at'], name='int_audit_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationtransitionaudit',
            index=models.Index(fields=['correlation_id'], name='int_audit_corr_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationtransitionaudit',
            constraint=models.UniqueConstraint(fields=('conversation', 'action', 'idempotency_key'), name='int_audit_action_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='integrationinboxevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='int_inbox_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationinboxevent',
            index=models.Index(fields=['conversation', 'status', 'received_at'], name='int_inbox_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationinboxevent',
            index=models.Index(fields=['correlation_id'], name='int_inbox_corr_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationinboxevent',
            index=models.Index(fields=['locked_at'], name='int_inbox_lock_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationinboxevent',
            constraint=models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='int_inbox_provider_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['conversation', 'received_at', 'id'], name='int_msg_conv_order_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['correlation_id'], name='int_msg_corr_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('provider', 'external_message_id'), name='int_msg_provider_ext_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externalmessagemapping',
            constraint=models.UniqueConstraint(fields=('provider', 'account_scope', 'external_id'), name='int_ext_message_uniq'),
        ),
        migrations.AddIndex(
            model_name='contextcheckpoint',
            index=models.Index(fields=['conversation', 'status', 'created_at'], name='int_checkpoint_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='botgeneration',
            index=models.Index(fields=['conversation', 'status', 'started_at'], name='int_gen_active_idx'),
        ),
        migrations.AddIndex(
            model_name='botgeneration',
            index=models.Index(fields=['correlation_id'], name='int_gen_corr_idx'),
        ),
        migrations.AddConstraint(
            model_name='botgeneration',
            constraint=models.UniqueConstraint(fields=('conversation', 'request_key'), name='int_gen_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attachmentmapping',
            constraint=models.UniqueConstraint(fields=('provider', 'external_attachment_id'), name='int_ext_attachment_uniq'),
        ),
        migrations.AddIndex(
            model_name='integrationoutboxevent',
            index=models.Index(fields=['status', 'available_at'], name='int_outbox_available_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoutboxevent',
            index=models.Index(fields=['conversation', 'status', 'created_at'], name='int_outbox_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoutboxevent',
            index=models.Index(fields=['correlation_id'], name='int_outbox_corr_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoutboxevent',
            index=models.Index(fields=['locked_at'], name='int_outbox_lock_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutboxevent',
            constraint=models.UniqueConstraint(fields=('destination', 'idempotency_key'), name='int_outbox_dest_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutboxevent',
            constraint=models.UniqueConstraint(condition=models.Q(('logical_message__isnull', False)), fields=('destination', 'logical_message', 'event_type'), name='int_outbox_logical_dest_uniq'),
        ),
    ]
