# Generated by Django 6.0.6 on 2026-08-08 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_correo_cliente_documento_and_more'),
        ('integrations', '0001_initial'),
        ('whatsapp', '0011_configuracionbot_asesor_predeterminado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentmapping',
            name='int_cw_agent_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='attachmentmapping',
            name='int_ext_attachment_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='channelinboxmapping',
            name='int_cw_inbox_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='chatwootaccountmapping',
            name='int_cw_account_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='chatwootcontactmapping',
            name='int_cw_contact_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='contactinboxmapping',
            name='int_cw_source_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='conversationmapping',
            name='int_cw_conversation_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='externalmessagemapping',
            name='int_ext_message_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='integrationinboxevent',
            name='int_inbox_provider_idem_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='integrationmessage',
            name='int_msg_provider_ext_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='integrationoutboxevent',
            name='int_outbox_dest_idem_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='integrationoutboxevent',
            name='int_outbox_logical_dest_uniq',
        ),
        migrations.AddField(
            model_name='attachmentmapping',
            name='external_scope',
            field=models.CharField(default='internal', max_length=160),
        ),
        migrations.AddField(
            model_name='chatwootcontactmapping',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integrationinboxevent',
            name='external_scope',
            field=models.CharField(default='internal', max_length=160),
        ),
        migrations.AddField(
            model_name='integrationinboxevent',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='whatsapp.whatsappchannel'),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='external_scope',
            field=models.CharField(default='internal', max_length=160),
        ),
        migrations.AddField(
            model_name='integrationoutboxevent',
            name='destination_scope',
            field=models.CharField(default='internal', max_length=160),
        ),
        migrations.AlterField(
            model_name='agentmapping',
            name='chatwoot_user_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentmapping',
            name='external_attachment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='channelinboxmapping',
            name='inbox_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='chatwootaccountmapping',
            name='account_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='chatwootcontactmapping',
            name='contact_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contactinboxmapping',
            name='source_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmapping',
            name='external_conversation_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='externalmessagemapping',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='integrationinboxevent',
            name='external_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='integrationmessage',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('document', 'Documento'), ('video', 'Video'), ('location', 'Ubicación'), ('contact', 'Contacto'), ('interactive_reply', 'Respuesta interactiva'), ('button', 'Botón'), ('list', 'Lista'), ('unsupported', 'No soportado')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='integrationmessage',
            name='external_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='integrationmessage',
            name='idempotency_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='agentmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('chatwoot_user_id__isnull', False), models.Q(('chatwoot_user_id', ''), _negated=True)), fields=('account', 'chatwoot_user_id'), name='int_cw_agent_uniq'),
        ),
        migrations.AddConstraint(
            model_name='agentmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('user__isnull', False)), fields=('account', 'user'), name='int_cw_active_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attachmentmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('external_attachment_id__isnull', False), models.Q(('external_attachment_id', ''), _negated=True)), fields=('provider', 'external_scope', 'external_attachment_id'), name='int_ext_attachment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='channelinboxmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('inbox_id__isnull', False), models.Q(('inbox_id', ''), _negated=True)), fields=('account', 'inbox_id'), name='int_cw_inbox_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chatwootaccountmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('account_id__isnull', False), models.Q(('account_id', ''), _negated=True)), fields=('environment', 'account_id'), name='int_cw_account_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chatwootcontactmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_id__isnull', False), models.Q(('contact_id', ''), _negated=True)), fields=('account', 'contact_id'), name='int_cw_contact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chatwootcontactmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('cliente', 'account'), name='int_client_active_contact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='contactinboxmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), models.Q(('source_id', ''), _negated=True)), fields=('inbox', 'source_id'), name='int_cw_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversationmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('external_conversation_id__isnull', False), models.Q(('external_conversation_id', ''), _negated=True)), fields=('contact_inbox', 'external_conversation_id'), name='int_cw_conversation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externalmessagemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('provider', 'account_scope', 'external_id'), name='int_ext_message_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationinboxevent',
            constraint=models.UniqueConstraint(fields=('provider', 'external_scope', 'idempotency_key'), name='int_inbox_scope_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationinboxevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id__isnull', False), models.Q(('external_event_id', ''), _negated=True)), fields=('provider', 'external_scope', 'external_event_id'), name='int_inbox_scope_ext_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id__isnull', False), models.Q(('external_message_id', ''), _negated=True)), fields=('provider', 'external_scope', 'external_message_id'), name='int_msg_scope_ext_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationmessage',
            constraint=models.UniqueConstraint(fields=('provider', 'external_scope', 'idempotency_key'), name='int_msg_scope_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutboxevent',
            constraint=models.UniqueConstraint(fields=('destination', 'destination_scope', 'idempotency_key'), name='int_outbox_scope_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutboxevent',
            constraint=models.UniqueConstraint(condition=models.Q(('logical_message__isnull', False)), fields=('destination', 'destination_scope', 'logical_message', 'event_type'), name='int_outbox_logical_dest_uniq'),
        ),
    ]
