# Generated by Django 6.0.6 on 2026-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_channel_ai_v31_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='botgeneration',
            name='asked_targets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
