# Generated by Django 6.0.6 on 2026-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_bot_generation_asked_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='botgeneration',
            name='conversation_intent',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='botgeneration',
            name='conversation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
