# Generated by Django 6.0.6 on 2026-06-12 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campo', '0002_add_fields_to_vehiculo_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('kilometraje_actual', models.PositiveIntegerField(verbose_name='Kilometraje actual')),
                ('proximo_mantenimiento_km', models.PositiveIntegerField(verbose_name='Próximo mantenimiento (km)')),
                ('descripcion', models.TextField(verbose_name='Trabajo realizado')),
                ('observaciones', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='campo.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Vehículo',
                'verbose_name_plural': 'Mantenimientos de Vehículos',
                'ordering': ['-fecha_mantenimiento'],
            },
        ),
    ]
