# Generated by Django 6.0.6 on 2026-06-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('leads', '0007_lead_fecha_por_confirmar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=160, unique=True)),
                ('archivo', models.FileField(upload_to='whatsapp/%Y/%m/')),
                ('mime_type', models.CharField(max_length=100)),
                ('sha256_meta', models.CharField(blank=True, max_length=128)),
                ('caption', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_whatsapp', to='clientes.cliente')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_whatsapp', to='leads.lead')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
