# Generated by Django 6.0.6 on 2026-06-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_mensajewhatsappprocesado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciawhatsapp',
            name='analisis_visual',
            field=models.TextField(blank=True),
        ),
    ]
