# Generated by Django 6.0.6 on 2026-06-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_evidenciawhatsapp_analisis_visual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_activo', models.BooleanField(default=True)),
                ('modo_atencion', models.CharField(choices=[('bot', 'Solo bot'), ('humano', 'Solo humano'), ('mixto', 'Mixto')], default='bot', max_length=10)),
                ('hora_inicio_bot', models.TimeField(default='07:00')),
                ('hora_fin_bot', models.TimeField(default='23:00')),
                ('lunes_activo', models.BooleanField(default=True)),
                ('martes_activo', models.BooleanField(default=True)),
                ('miercoles_activo', models.BooleanField(default=True)),
                ('jueves_activo', models.BooleanField(default=True)),
                ('viernes_activo', models.BooleanField(default=True)),
                ('sabado_activo', models.BooleanField(default=True)),
                ('domingo_activo', models.BooleanField(default=False)),
                ('mensaje_fuera_horario', models.TextField(blank=True, default='Gracias por contactarnos. Nuestro horario de atencion es de Lunes a Sabado de 7:00 a 23:00. Un asesor te atenderá en breve.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del bot',
                'verbose_name_plural': 'Configuración del bot',
            },
        ),
    ]
