# Generated by Django 6.0.6 on 2026-06-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_configuracion_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario del bot',
                'verbose_name_plural': 'Horarios del bot',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='override_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='override_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='override_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='override_modo',
            field=models.CharField(choices=[('none', 'Ninguno'), ('force_bot', 'Forzar bot'), ('force_human', 'Forzar humano')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='override_motivo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
