# Generated by Django 6.0.6 on 2026-06-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_botschedule_configuracionbot_override_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionbot',
            name='override_modo',
            field=models.CharField(choices=[('none', 'Ninguno'), ('force_bot', 'Forzar bot'), ('force_human', 'Forzar humano'), ('force_mixto', 'Forzar mixto inteligente')], default='none', max_length=12),
        ),
    ]
