# Generated by Django 6.0.6 on 2026-06-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_alter_configuracionbot_override_modo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('phone_number_id', models.CharField(max_length=30, unique=True)),
                ('numero_visible', models.CharField(blank=True, default='', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canales_whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal WhatsApp',
                'verbose_name_plural': 'Canales WhatsApp',
            },
        ),
        migrations.AddField(
            model_name='botschedule',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bot', to='whatsapp.whatsappchannel'),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_bot', to='whatsapp.whatsappchannel'),
        ),
    ]
