# Generated by Django 6.0.6 on 2026-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsappchannel_botschedule_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botschedule',
            name='modo',
            field=models.CharField(choices=[('bot', 'Bot automático'), ('mixto', 'Bot mixto inteligente')], default='bot', max_length=20),
        ),
    ]
