# Generated by Django 6.0.6 on 2026-08-07 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_correo_cliente_documento_and_more'),
        ('leads', '0012_lead_whatsapp_channel'),
        ('whatsapp', '0008_add_modo_to_botschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_atencion', models.CharField(choices=[('bot', 'Bot atendiendo'), ('asesor', 'Asesor atendiendo'), ('cerrada', 'Cerrada')], default='bot', max_length=20)),
                ('estado_recopilacion', models.CharField(choices=[('nueva', 'Nueva'), ('en_proceso', 'En proceso'), ('esperando_cliente', 'Esperando al cliente'), ('completa', 'Completa')], default='nueva', max_length=30)),
                ('estado_cotizacion', models.CharField(choices=[('sin_iniciar', 'Sin iniciar'), ('por_cotizar', 'Por cotizar'), ('precio_enviado', 'Precio enviado'), ('cerrada', 'Cerrada')], default='sin_iniciar', max_length=30)),
                ('bot_pausado', models.BooleanField(default=False)),
                ('instruccion_retorno_bot', models.CharField(blank=True, max_length=40)),
                ('resumen', models.TextField(blank=True)),
                ('datos_faltantes', models.JSONField(blank=True, default=list)),
                ('porcentaje_informacion', models.PositiveSmallIntegerField(default=0)),
                ('motivo_derivacion', models.TextField(blank=True)),
                ('ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_mensaje_cliente', models.DateTimeField(blank=True, null=True)),
                ('ultimo_mensaje_enviado', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='whatsapp.whatsappchannel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_whatsapp', to='clientes.cliente')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_whatsapp', to='leads.lead')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=80)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria_whatsapp', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_whatsapp', to='leads.lead')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='whatsapp.conversacionwhatsapp')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_message_id', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10)),
                ('origen', models.CharField(choices=[('cliente', 'Cliente'), ('bot', 'Bot'), ('asesor', 'Asesor'), ('sistema', 'Sistema')], max_length=10)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('audio', 'Audio'), ('documento', 'Documento'), ('ubicacion', 'Ubicacion'), ('sistema', 'Sistema')], default='texto', max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leido'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('error_codigo', models.CharField(blank=True, max_length=80)),
                ('error_detalle', models.TextField(blank=True)),
                ('fecha_mensaje', models.DateTimeField(default=django.utils.timezone.now)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacionwhatsapp')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='whatsapp.evidenciawhatsapp')),
            ],
            options={
                'ordering': ['fecha_mensaje', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacionwhatsapp',
            index=models.Index(fields=['channel', 'estado_atencion', '-ultima_actividad'], name='whatsapp_co_channel_c5bf15_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionwhatsapp',
            index=models.Index(fields=['estado_cotizacion', '-ultima_actividad'], name='whatsapp_co_estado__02dc3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversacionwhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False), models.Q(('estado_atencion', 'cerrada'), _negated=True)), fields=('lead',), name='whatsapp_lead_conversacion_activa_unica'),
        ),
        migrations.AddConstraint(
            model_name='conversacionwhatsapp',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_informacion__gte', 0), ('porcentaje_informacion__lte', 100)), name='whatsapp_porcentaje_informacion_valido'),
        ),
        migrations.AddIndex(
            model_name='auditoriawhatsapp',
            index=models.Index(fields=['conversacion', '-creado_en'], name='whatsapp_au_convers_174a08_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['conversacion', 'fecha_mensaje'], name='whatsapp_me_convers_60d854_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['estado', 'fecha_mensaje'], name='whatsapp_me_estado_e68871_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensajewhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('meta_message_id', ''), _negated=True), fields=('meta_message_id',), name='whatsapp_meta_message_id_unico'),
        ),
    ]
