# Generated by Django 6.0.6 on 2026-08-07 16:06

from django.db import migrations


def crear_conversaciones_desde_leads(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    ConversacionWhatsApp = apps.get_model("whatsapp", "ConversacionWhatsApp")
    for lead in Lead.objects.select_related("cliente").iterator():
        cerrada = lead.estado in ["cerrado", "perdido"]
        humana = bool(lead.atencion_humana or lead.bot_pausado or lead.requiere_asesor)
        estado_atencion = "cerrada" if cerrada else ("asesor" if humana else "bot")
        precio_enviado = bool(lead.precio_cotizado or lead.estado in ["cotizado", "cerrado"])
        ConversacionWhatsApp.objects.get_or_create(
            lead_id=lead.id,
            defaults={
                "cliente_id": lead.cliente_id,
                "channel_id": lead.whatsapp_channel_id,
                "responsable_id": lead.vendedor_asignado_id if humana and not cerrada else None,
                "estado_atencion": estado_atencion,
                "estado_recopilacion": "completa" if precio_enviado else "en_proceso",
                "estado_cotizacion": "precio_enviado" if precio_enviado else "sin_iniciar",
                "bot_pausado": humana or cerrada,
                "motivo_derivacion": lead.motivo_derivacion or "",
                "cerrada_en": lead.fecha_cierre if cerrada else None,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_conversacionwhatsapp_auditoriawhatsapp_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_conversaciones_desde_leads, migrations.RunPython.noop),
    ]
