# Generated by Django 6.0.6 on 2026-08-07 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mapear_modos(apps, schema_editor):
    ConfiguracionBot = apps.get_model('whatsapp', 'ConfiguracionBot')
    mapping = {'humano': 'asesor', 'bot': 'automatica', 'mixto': 'hibrido'}
    for config in ConfiguracionBot.objects.all():
        config.modo_operacion = mapping.get(config.modo_atencion, 'automatica')
        config.save(update_fields=['modo_operacion'])


def revertir_modos(apps, schema_editor):
    ConfiguracionBot = apps.get_model('whatsapp', 'ConfiguracionBot')
    mapping = {'asesor': 'humano', 'recopilar': 'bot', 'automatica': 'bot', 'hibrido': 'mixto'}
    for config in ConfiguracionBot.objects.all():
        config.modo_atencion = mapping.get(config.modo_operacion, 'bot')
        config.save(update_fields=['modo_atencion'])


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_backfill_conversaciones_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionbot',
            name='asesor_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_bot_predeterminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='confianza_minima',
            field=models.DecimalField(decimal_places=2, default=85, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='espera_asesor_minutos',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='margen_minimo_porcentaje',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='mensaje_bienvenida',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='modo_operacion',
            field=models.CharField(choices=[('asesor', 'Solo asesor'), ('recopilar', 'Recopilar datos'), ('automatica', 'Cotización automática'), ('hibrido', 'Híbrido')], default='automatica', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='reglas_automaticas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='seguimiento_horas',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='transferir_fuera_horario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='zona_horaria',
            field=models.CharField(default='America/Lima', max_length=64),
        ),
        migrations.RunPython(mapear_modos, revertir_modos),
    ]
