# Generated by Django 6.0.6 on 2026-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0012_mensajewhatsapp_question_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='pending_request_switch',
            field=models.BooleanField(default=False),
        ),
    ]
