# Generated by Django 6.0.8 on 2026-08-21 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0015_create_mensaje_adjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mensajeadjunto',
            new_name='whatsapp_me_mensaje_6d2c21_idx',
            old_name='whatsapp_me_mensaje_48c9f7_idx',
        ),
        migrations.RenameIndex(
            model_name='mensajeadjunto',
            new_name='whatsapp_me_retain__f3d147_idx',
            old_name='whatsapp_me_retain__50e2d4_idx',
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='media_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending download'), ('downloading', 'Downloading'), ('ready', 'Ready (file saved)'), ('failed', 'Download failed'), ('expired', 'URL expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='protected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_protegidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='protected_from_cleanup',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='protection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='protection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='retention_policy',
            field=models.CharField(choices=[('default', 'Default (30 days)'), ('quote', 'Quote-linked (60 days)'), ('service', 'Service-linked (90 days)'), ('claim', 'Claim (no limit)'), ('none', 'No cleanup')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('bot', 'Bot'), ('advisor', 'Advisor'), ('system', 'System')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='source',
            field=models.CharField(choices=[('whatsapp_customer', 'WhatsApp Customer (inbound)'), ('whatsapp_business_app', 'WhatsApp Business App (Web/mobile echo)'), ('bot', 'Bot (automated response)'), ('crm', 'CRM (advisor manual entry)'), ('system', 'System (automated action)')], default='whatsapp_customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='ycloud_media_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
