# Generated by Django 6.0.8 on 2026-08-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0017_add_conversation_read_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
