# Generated by Django 6.0.8 on 2026-08-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0018_add_unique_active_conversation_constraint'),
        ('whatsapp', '0018_alter_conversacionwhatsapp_ultima_actividad'),
    ]

    operations = [
    ]
