# Generated by Django 6.0.8 on 2026-08-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0019_merge_20260821_1524'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversacionwhatsapp',
            name='unique_active_whatsapp_conversation',
        ),
    ]
