# Generated by Django 6.0.6 on 2026-08-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0020_remove_conversacionwhatsapp_unique_active_whatsapp_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='responde_a',
            field=models.ForeignKey(blank=True, help_text='Mensaje citado (quote-reply). NULL si no responde a nada, o si el mensaje citado fue borrado — la cita se pierde, nunca el mensaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='whatsapp.mensajewhatsapp'),
        ),
    ]
