# Generated by Django 6.0.6 on 2026-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0021_mensajewhatsapp_responde_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='wamid',
            field=models.CharField(blank=True, default='', help_text="wamid real de WhatsApp/Meta (formato 'wamid.XXXX'), requerido por YCloud para citar un mensaje (context.message_id) en una respuesta. Distinto de meta_message_id, que es el id interno de YCloud (formato hex corto) usado para correlación de eventos/estado — nunca sirve para citar.", max_length=255),
        ),
    ]
