# Generated by Django 6.0.6 on 2026-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0022_mensajewhatsapp_wamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='reaction_emoji',
            field=models.CharField(blank=True, default='', help_text="Emoji de reacción actual sobre ESTE mensaje (uno solo, como WhatsApp 1:1 — la última reacción reemplaza a la anterior). Vacío = sin reacción. YCloud manda '' explícito cuando el usuario quita su reacción.", max_length=8),
        ),
    ]
