# Generated by Django 6.0.6 on 2026-08-29 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0023_mensajewhatsapp_reaction_emoji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='oculto_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se ocultó (auditoría).', null=True),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='oculto_en_crm',
            field=models.BooleanField(default=False, help_text="'Ocultar en el CRM' — solo deja de mostrarse en el timeline y en el preview de la bandeja (para TODOS los usuarios del CRM, no solo quien lo ocultó — es una bandeja compartida). NUNCA borra el registro: es evidencia comercial de cotizaciones. No afecta al WhatsApp del cliente en absoluto — eso no es técnicamente posible (YCloud no expone ningún endpoint de revocación)."),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='oculto_por',
            field=models.ForeignKey(blank=True, help_text='Quién ocultó este mensaje (auditoría).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
