# Generated by Django 6.0.6 on 2026-08-29 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0024_mensajewhatsapp_oculto_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='archivada',
            field=models.BooleanField(default=False, help_text="Estado del CRM únicamente — no afecta al WhatsApp real del cliente ni del asesor. Sale de la bandeja principal a la pestaña 'Archivados'. Se reactiva sola cuando el cliente escribe un mensaje nuevo (mismo comportamiento que archivar un chat en WhatsApp real)."),
        ),
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='archivada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='archivada_por',
            field=models.ForeignKey(blank=True, help_text='Quién archivó esta conversación (auditoría). NULL si se desarchivó automáticamente por un mensaje nuevo del cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
