# Generated by Django 6.0.6 on 2026-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0025_conversacionwhatsapp_archivada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='datos_extraidos',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de servicio detectados por la extracción NLU antes de que exista un Lead (tipo_servicio, distrito_origen/destino, pisos, ascensor, objetos, fecha…). Cuando alcanza el mínimo para cotizar se crea el Lead y a partir de ahí la extracción llena el Lead directamente. El panel de la bandeja lee de aquí o del Lead.'),
        ),
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='ultima_extraccion_en',
            field=models.DateTimeField(blank=True, help_text='Última vez que el barrido de extracción procesó esta conversación. El barrido se salta las conversaciones sin mensajes entrantes nuevos desde esta marca.', null=True),
        ),
    ]
