# Generated by Django 6.0.6 on 2026-09-06 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0026_conversacionwhatsapp_datos_extraidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_rapidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta rápida',
                'verbose_name_plural': 'Respuestas rápidas',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
