# Generated by Django 6.0.6 on 2026-09-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0027_respuestarapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestarapida',
            name='tipo',
            field=models.CharField(choices=[('respuesta', 'Respuesta rápida'), ('cotizacion', 'Mensaje de cotización')], db_index=True, default='respuesta', max_length=20),
        ),
    ]
