# Generated by Django 6.0.6 on 2026-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0028_respuestarapida_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestarapida',
            name='tipo',
            field=models.CharField(choices=[('respuesta', 'Respuesta rápida'), ('cotizacion', 'Mensaje de cotización (nueva)'), ('recotizacion', 'Mensaje de re-cotización')], db_index=True, default='respuesta', max_length=20),
        ),
    ]
