# Generated by Django 6.0.6 on 2026-06-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(blank=True, max_length=80)),
                ('distrito_origen', models.CharField(blank=True, max_length=120)),
                ('distrito_destino', models.CharField(blank=True, max_length=120)),
                ('direccion_origen', models.CharField(blank=True, max_length=255)),
                ('direccion_destino', models.CharField(blank=True, max_length=255)),
                ('piso_origen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('piso_destino', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ascensor_origen', models.BooleanField(blank=True, null=True)),
                ('ascensor_destino', models.BooleanField(blank=True, null=True)),
                ('lista_objetos', models.TextField(blank=True)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('horario_servicio', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_conversacion', 'En conversacion'), ('datos_incompletos', 'Datos incompletos'), ('cotizado', 'Cotizado'), ('asignado', 'Asignado'), ('cerrado', 'Cerrado'), ('perdido', 'Perdido')], default='nuevo', max_length=30)),
                ('precio_estimado_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_estimado_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_recomendado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_cotizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clientes.cliente')),
                ('vendedor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
