# Generated by Django 6.0.6 on 2026-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_fecha_cierre_lead_fecha_ultimo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='atencion_humana',
            field=models.BooleanField(default=False),
        ),
    ]
