# Generated by Django 6.0.6 on 2026-06-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_atencion_humana'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fecha_proximo_seguimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
