# Generated by Django 6.0.6 on 2026-06-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_fecha_proximo_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='acceso_destino',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='acceso_origen',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='capacidad_camion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='distancia_carga_destino_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='distancia_carga_origen_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='dni_reserva',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='etapa_conversacion',
            field=models.CharField(choices=[('cotizacion', 'Cotizacion'), ('reserva', 'Reserva'), ('reservado', 'Reservado')], default='cotizacion', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='modalidad_servicio',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lead',
            name='objetos_pesados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='peso_carga_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='requiere_desarmado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tipo_camion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='volumen_carga_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
