# Generated by Django 6.0.6 on 2026-06-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_acceso_destino_lead_acceso_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='camion_llega_destino',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='camion_llega_origen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
