# Generated by Django 6.0.6 on 2026-06-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_camion_llega_destino_lead_camion_llega_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fecha_por_confirmar',
            field=models.BooleanField(default=False),
        ),
    ]
