# Generated by Django 6.0.6 on 2026-06-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_fecha_por_confirmar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='incluye_personal_carga',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
