# Generated by Django 6.0.6 on 2026-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_incluye_personal_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='esperando_motivo_no_reserva',
            field=models.BooleanField(default=False),
        ),
    ]
