# Generated by Django 6.0.6 on 2026-06-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_horario_por_confirmar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bot_pausado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_derivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='motivo_derivacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='requiere_asesor',
            field=models.BooleanField(default=False),
        ),
    ]
