# Generated by Django 6.0.6 on 2026-06-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_mixto_inteligente'),
        ('whatsapp', '0007_whatsappchannel_botschedule_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='whatsapp_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='whatsapp.whatsappchannel'),
        ),
    ]
