# Generated by Django 6.0.6 on 2026-08-09 19:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_lead_locations(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    LeadUbicacion = apps.get_model("leads", "LeadUbicacion")
    rows = []
    for lead in Lead.objects.all().iterator(chunk_size=500):
        origin_values = (
            lead.distrito_origen, lead.direccion_origen, lead.piso_origen,
            lead.ascensor_origen, lead.camion_llega_origen,
            lead.distancia_carga_origen_m, lead.acceso_origen,
        )
        destination_values = (
            lead.distrito_destino, lead.direccion_destino, lead.piso_destino,
            lead.ascensor_destino, lead.camion_llega_destino,
            lead.distancia_carga_destino_m, lead.acceso_destino,
        )
        order = 0
        if any(value not in (None, "") for value in origin_values):
            rows.append(LeadUbicacion(
                lead_id=lead.pk, orden=order, tipo="origen",
                distrito=lead.distrito_origen, direccion=lead.direccion_origen,
                piso=lead.piso_origen, ascensor=lead.ascensor_origen,
                acceso_camion=lead.camion_llega_origen,
                distancia_acarreo=lead.distancia_carga_origen_m,
                observaciones_acceso=lead.acceso_origen,
            ))
            order += 1
        if any(value not in (None, "") for value in destination_values):
            rows.append(LeadUbicacion(
                lead_id=lead.pk, orden=order, tipo="destino",
                distrito=lead.distrito_destino, direccion=lead.direccion_destino,
                piso=lead.piso_destino, ascensor=lead.ascensor_destino,
                acceso_camion=lead.camion_llega_destino,
                distancia_acarreo=lead.distancia_carga_destino_m,
                observaciones_acceso=lead.acceso_destino,
            ))
        if len(rows) >= 1000:
            LeadUbicacion.objects.bulk_create(rows)
            rows = []
    if rows:
        LeadUbicacion.objects.bulk_create(rows)


def reverse_backfill(apps, schema_editor):
    apps.get_model("leads", "LeadUbicacion").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_whatsapp_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cantidad_operarios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='requiere_armado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LeadUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('origen', 'Origen'), ('parada', 'Parada'), ('destino', 'Destino')], max_length=12)),
                ('distrito', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('piso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ascensor', models.BooleanField(blank=True, null=True)),
                ('acceso_camion', models.BooleanField(blank=True, null=True)),
                ('distancia_acarreo', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones_acceso', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='leads.lead')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['lead', 'tipo', 'orden'], name='leads_leadu_lead_id_089372_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'orden'), name='lead_ubicacion_orden_unico'), models.UniqueConstraint(condition=models.Q(('tipo__in', ['origen', 'destino'])), fields=('lead', 'tipo'), name='lead_ubicacion_extremo_unico')],
            },
        ),
        migrations.RunPython(backfill_lead_locations, reverse_backfill),
    ]
