# Generated by Django 6.0.6 on 2026-09-03 16:40

from django.db import migrations, models


_KEYWORDS = (
    ("precio", ("precio", "caro", "presupuesto", "costo", "barato", "economic")),
    ("tiempo_respuesta", ("tiempo", "demor", "tard", "respuesta lenta", "lento", "muy tarde", "rapidez")),
    ("competencia", ("competencia", "otro proveedor", "otra empresa", "eligio a otro", "eligió a otro", "contrato a otro", "proveedor")),
    ("no_responde", ("no responde", "no contesta", "no contestó", "dejo de responder", "dejó de responder", "sin respuesta", "no volvio", "no volvió")),
    ("fuera_cobertura", ("cobertura", "no llegamos", "muy lejos", "fuera de zona", "no cubrimos")),
)
_CODES = {"precio", "tiempo_respuesta", "competencia", "no_responde", "fuera_cobertura", "otro"}


def _map(texto):
    valor = (texto or "").strip().lower()
    if not valor or valor in _CODES:
        return valor
    for codigo, claves in _KEYWORDS:
        if any(clave in valor for clave in claves):
            return codigo
    return "otro"


def migrar_motivo_perdida(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    for lead in Lead.objects.exclude(motivo_perdida="").iterator():
        original = lead.motivo_perdida
        codigo = _map(original)
        if codigo == original:
            continue
        lead.motivo_perdida = codigo
        if not lead.motivo_perdida_detalle:
            lead.motivo_perdida_detalle = original
        lead.save(update_fields=["motivo_perdida", "motivo_perdida_detalle"])


def revertir_motivo_perdida(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    for lead in Lead.objects.exclude(motivo_perdida_detalle="").iterator():
        lead.motivo_perdida = lead.motivo_perdida_detalle
        lead.save(update_fields=["motivo_perdida"])


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_ordered_locations_and_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='es_interprovincial',
            field=models.BooleanField(default=False, help_text='Ruta fuera de Lima Metropolitana (interprovincial o de provincia). La marca la extracción NLU; el cotizador automático no cubre estas rutas.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='motivo_perdida_detalle',
            field=models.TextField(blank=True, help_text='Detalle libre del motivo de pérdida, tal como lo escribió el asesor.'),
        ),
        migrations.RunPython(migrar_motivo_perdida, revertir_motivo_perdida),
        migrations.AlterField(
            model_name='lead',
            name='motivo_perdida',
            field=models.CharField(blank=True, choices=[('precio', 'Precio'), ('tiempo_respuesta', 'Tiempo de respuesta'), ('competencia', 'Competencia'), ('no_responde', 'No responde'), ('fuera_cobertura', 'Fuera de cobertura'), ('otro', 'Otro')], help_text='Motivo canónico de pérdida (para reportes).', max_length=255),
        ),
    ]
