# Generated by Django 6.0.6 on 2026-09-09 16:05
from django.db import migrations, models


def poblar_codigos(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    n = 0
    for lead in Lead.objects.filter(codigo="").order_by("id").iterator():
        n += 1
        Lead.objects.filter(pk=lead.pk).update(codigo=f"CRG-{lead.id:04d}")
    return n


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_persona_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='categoria_carga',
            field=models.CharField(blank=True, choices=[('mudanza', 'Mudanza, muebles y electrodomésticos'), ('cajas', 'Cajas, paquetes y bultos'), ('mercaderia', 'Mercadería comercial'), ('maquinaria', 'Maquinaria y equipos'), ('construccion', 'Materiales de construcción'), ('agricolas', 'Productos agrícolas'), ('pallets', 'Pallets / parihuelas'), ('contenedores', 'Contenedores'), ('refrigerada', 'Carga refrigerada'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='modo_cotizacion',
            field=models.CharField(blank=True, choices=[('por_carga', 'Por carga'), ('por_vehiculo', 'Por vehículo')], max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='origen_carga',
            field=models.CharField(choices=[('bot_whatsapp', 'Bot de WhatsApp'), ('invitado', 'Cotización rápida (invitado)'), ('portal_cliente', 'Portal del cliente'), ('asesor_telefono', 'Asesor · teléfono'), ('asesor_correo', 'Asesor · correo'), ('asesor_crm', 'Asesor · CRM')], default='bot_whatsapp', max_length=20),
        ),
        # `codigo`: primero sin unique ni índice, se puebla, luego se marca unique.
        migrations.AddField(
            model_name='lead',
            name='codigo',
            field=models.CharField(blank=True, default='', help_text='Código único de la carga (CRG-NNNN). El Servicio adopta este mismo código.', max_length=20),
        ),
        migrations.RunPython(poblar_codigos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lead',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Código único de la carga (CRG-NNNN). El Servicio adopta este mismo código.', max_length=20, unique=True),
        ),
    ]
