# Generated by Django 6.0.6 on 2026-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_lead_categoria_carga_lead_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lat_destino',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lat_origen',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lng_destino',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lng_origen',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='provincia_destino',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='provincia_origen',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='region_destino',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='region_origen',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leadubicacion',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='leadubicacion',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='leadubicacion',
            name='provincia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leadubicacion',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
