# Generated by Django 6.0.6 on 2026-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_lead_lat_destino_lead_lat_origen_lead_lng_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='modo_carga',
            field=models.CharField(choices=[('completa', 'Completa (camión dedicado)'), ('parcial', 'Parcial (consolidada con otra carga del transportista)')], default='completa', help_text="Solo relevante si es_interprovincial=True. 'parcial' cotiza por la tabla TarifaCargaParcial (peso × ruta) en vez del camión dedicado.", max_length=10),
        ),
    ]
