# Generated by Django 6.0.6 on 2026-09-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_lead_modo_carga'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='leads/fotos/%Y/%m/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='leads.lead')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
