# Generated by Django 6.0.6 on 2026-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_leadfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='precio_propuesto_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio real que el cliente ofrece pagar al publicar (opción 'Publicar con mi precio', en vez de recibir ofertas). Lo ve el asesor al cotizar — las comisiones se siguen calculando igual que siempre sobre lo que finalmente se acuerde.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='precio_propuesto_negociable',
            field=models.BooleanField(default=True),
        ),
    ]
