# Generated by Django 6.0.6 on 2026-06-05 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=160)),
                ('telefono', models.CharField(max_length=30, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_interaccion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-ultima_interaccion'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_entrada', models.TextField(blank=True)),
                ('mensaje_salida', models.TextField(blank=True)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
