# Generated by Django 6.0.8 on 2026-08-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_correo_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text="List of historical names: ['TEST Stage 7', 'ELI ESCOBAR', ...]"),
        ),
        migrations.AddField(
            model_name='cliente',
            name='channel_profile_name',
            field=models.CharField(blank=True, help_text='Name from WhatsApp profile', max_length=160),
        ),
        migrations.AddField(
            model_name='cliente',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name displayed in CRM (manual or best-match)', max_length=160),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivated if merged or duplicate'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='If not null, this cliente has been merged into another', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='name_source',
            field=models.CharField(choices=[('manual', 'Manual (CRM)'), ('crm', 'CRM/Lead'), ('channel', 'WhatsApp Channel'), ('import', 'Import'), ('fallback', 'Fallback (phone)')], default='fallback', help_text='Source of display_name', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized phone in E.164 format (+51995403320)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['phone_e164'], name='clientes_cl_phone_e_907dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['is_active', '-ultima_interaccion'], name='clientes_cl_is_acti_c0c935_idx'),
        ),
    ]
