# Generated by Django 6.0.6 on 2026-08-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_aliases_cliente_channel_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ycloud_user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="YCloud internal fromUserId — fallback identity when the webhook omits 'from' (e.g. reply/quote messages)", max_length=64),
        ),
    ]
