# Generated by Django 6.0.6 on 2026-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_ycloud_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_transportista',
            field=models.BooleanField(db_index=True, default=False, help_text="Marcado automáticamente al detectar un mensaje 'OFERTA-<código>' (tercerización de cargas). Reversible manualmente desde la ficha del contacto — no es un estado que deba quedar atrapado por error."),
        ),
    ]
