# Generated by Django 6.0.6 on 2026-08-30 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_es_transportista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_transportista_marcado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_transportista_marcado_por',
            field=models.ForeignKey(blank=True, help_text='Quién marcó/desmarcó es_transportista. NULL = detección automática (Fase 2, por código OFERTA-<código> válido).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
