# Generated by Django 6.0.6 on 2026-09-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_es_transportista_marcado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_oficina',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
