# Generated by Django 6.0.6 on 2026-09-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_es_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_campo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
