# Generated by Django 6.0.6 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_es_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('ocasional', 'Ocasional'), ('frecuente', 'Frecuente'), ('empresa', 'Empresa')], db_index=True, default='ocasional', help_text='Ocasional (guest), Frecuente (carga recurrente) o Empresa (con cuenta/portal).', max_length=12),
        ),
    ]
