# Generated by Django 6.0.6 on 2026-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_internos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupointerno',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
