# Generated by Django 6.0.6 on 2026-09-08 02:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campo', '0007_alter_programacionservicio_conductor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conductor', 'Conductor'), ('ayudante', 'Ayudante'), ('asesor', 'Asesor')], max_length=12)),
                ('horas_jornada', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4, verbose_name='Horas de jornada')),
                ('horas_refrigerio', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Horas de refrigerio')),
                ('tipo_contrato', models.CharField(choices=[('honorarios', 'Recibo por honorarios'), ('planilla', 'Planilla')], max_length=12)),
                ('monto_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto por día (honorarios)')),
                ('monto_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto por mes (planilla)')),
                ('pct_afp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% AFP')),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ayudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_planilla', to='campo.ayudante')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_planilla', to='campo.conductor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_planilla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de planilla',
                'verbose_name_plural': 'Configuraciones de planilla',
                'ordering': ['tipo', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('conductor__isnull', False)), fields=('conductor',), name='planilla_config_conductor_unico'), models.UniqueConstraint(condition=models.Q(('ayudante__isnull', False)), fields=('ayudante',), name='planilla_config_ayudante_unico'), models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('usuario',), name='planilla_config_usuario_unico'), models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'conductor'), ('conductor__isnull', False), ('ayudante__isnull', True), ('usuario__isnull', True)), models.Q(('tipo', 'ayudante'), ('ayudante__isnull', False), ('conductor__isnull', True), ('usuario__isnull', True)), models.Q(('tipo', 'asesor'), ('usuario__isnull', False), ('conductor__isnull', True), ('ayudante__isnull', True)), _connector='OR'), name='planilla_config_link_coherente')],
            },
        ),
    ]
