# Generated by Django 6.0.6 on 2026-09-08 02:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_dia', models.CharField(choices=[('trabajado', 'Trabajado'), ('falta', 'Falta'), ('vacaciones', 'Vacaciones'), ('descanso', 'Descanso / franco'), ('feriado', 'Feriado'), ('licencia_sin_goce', 'Licencia sin goce')], default='trabajado', max_length=20)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('horas_jornada_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_refrigerio_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('delta_dia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='planilla.configuracionplanilla')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-fecha', 'id'],
                'constraints': [models.UniqueConstraint(fields=('trabajador', 'fecha'), name='planilla_asistencia_unica_por_dia')],
            },
        ),
    ]
