# Generated by Django 6.0.6 on 2026-09-08 13:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0002_registroasistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCompensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('falta_compensada', 'Falta compensada con horas'), ('dia_libre', 'Día libre a cuenta de horas'), ('pago_horas', 'Pago de horas extra'), ('devolucion_trabajador', 'El trabajador repone horas'), ('ajuste', 'Ajuste manual')], max_length=24)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensaciones', to='planilla.registroasistencia')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensaciones', to='planilla.configuracionplanilla')),
            ],
            options={
                'verbose_name': 'Movimiento de compensación',
                'verbose_name_plural': 'Movimientos de compensación',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoHorasMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('saldo_apertura', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('editado_manual', models.BooleanField(default=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_mes', to='planilla.configuracionplanilla')),
            ],
            options={
                'verbose_name': 'Saldo de horas del mes',
                'verbose_name_plural': 'Saldos de horas por mes',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('trabajador', 'anio', 'mes'), name='planilla_saldo_mes_unico')],
            },
        ),
    ]
