# Generated by Django 6.0.6 on 2026-09-08 13:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0003_movimientocompensacion_saldohorasmes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('quincena', 'Quincena'), ('fin_de_mes', 'Fin de mes'), ('adelanto', 'Adelanto / otro')], max_length=12)),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField()),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('dias_falta_descontados', models.PositiveSmallIntegerField(default=0)),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_afp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('otros_descuentos_motivo', models.CharField(blank=True, max_length=200)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=40)),
                ('nota', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='planilla.configuracionplanilla')),
            ],
            options={
                'verbose_name': 'Pago de planilla',
                'verbose_name_plural': 'Pagos de planilla',
                'ordering': ['-periodo_hasta', '-id'],
            },
        ),
    ]
