# Generated by Django 6.0.6 on 2026-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('quincena', 'Quincena'), ('fin_de_mes', 'Fin de mes'), ('por_dias', 'Por días (proporcional)'), ('adelanto', 'Adelanto / otro')], max_length=12),
        ),
    ]
