# Generated by Django 6.0.6 on 2026-09-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0005_alter_pago_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionplanilla',
            name='fecha_cese',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cese'),
        ),
    ]
