# Generated by Django 6.0.6 on 2026-09-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('icono', models.CharField(blank=True, max_length=60)),
                ('habilitado', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de carrocería',
                'verbose_name_plural': 'Tipos de carrocería',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('icono', models.CharField(blank=True, help_text="Clase de Remix Icon, p. ej. 'ri-truck-line'", max_length=60)),
                ('habilitado', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de vehículo',
                'verbose_name_plural': 'Tipos de vehículo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="p. ej. 'Camión 6 ton'", max_length=80)),
                ('categoria', models.CharField(choices=[('livianos', 'Livianos'), ('medianos', 'Medianos'), ('pesados', 'Pesados')], default='livianos', max_length=20)),
                ('min_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('habilitado', models.BooleanField(default=True)),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='catalogo.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Categoría de vehículo',
                'verbose_name_plural': 'Categorías de vehículo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carroceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='catalogo.tipocarroceria')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='catalogo.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Compatibilidad vehículo–carrocería',
                'verbose_name_plural': 'Compatibilidades vehículo–carrocería',
                'constraints': [models.UniqueConstraint(fields=('tipo_vehiculo', 'tipo_carroceria'), name='catalogo_compat_unica')],
            },
        ),
    ]
