# Generated by Django 6.0.6 on 2026-09-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_seed_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriavehiculo',
            name='categoria',
            field=models.CharField(choices=[('menores', 'Menores'), ('livianos', 'Livianos'), ('medianos', 'Medianos'), ('pesados', 'Pesados'), ('especiales', 'Especiales')], default='livianos', max_length=20),
        ),
    ]
