# Generated by Django 6.0.6 on 2026-09-17 17:23

from django.db import migrations, models

# Preserva el comportamiento actual (antes hardcodeado en
# apps/catalogo/api/views.py::_VEHICLE_CODES_PUBLICOS) al agregar el campo:
# solo Camioneta/Camión quedan visibles en el cotizador público de Carga.
_VISIBLES_HOY = ["camioneta", "camion"]


def _seed_visible_cotizador_publico(apps, schema_editor):
    TipoVehiculo = apps.get_model("catalogo", "TipoVehiculo")
    TipoVehiculo.objects.filter(codigo__in=_VISIBLES_HOY).update(visible_cotizador_publico=True)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_categoriavehiculo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovehiculo',
            name='visible_cotizador_publico',
            field=models.BooleanField(default=False, help_text="Si aparece como opción en el selector de vehículo del cotizador público de Carga (invitado/portal cliente). Antes era una lista fija en el código (_VEHICLE_CODES_PUBLICOS) que no se podía tocar desde acá — p. ej. Moto/Auto/Minivan no aplican a 'carga', y Semitrailer/Camión Remolque son carga muy pesada/especial que hoy pasa siempre por un asesor, no por el cotizador rápido. Se deja editable para no tener que tocar código si eso cambia."),
        ),
        migrations.RunPython(_seed_visible_cotizador_publico, _noop),
    ]
