# Generated by Django 6.0.6 on 2026-09-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_compatibilidad_por_categoria_finalizar'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilidadcarroceria',
            name='nombre_cliente',
            field=models.CharField(blank=True, default='', help_text="Nombre propio para mostrar al cliente en el cotizador (p. ej. 'Cigüeña'). Vacío = se muestra solo como carrocería dentro de la categoría, como siempre.", max_length=80),
        ),
    ]
