# Generated by Django 6.0.6 on 2026-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_compatibilidadcarroceria_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilidadcarroceria',
            name='categoria_cliente',
            field=models.CharField(blank=True, choices=[('menores', 'Menores'), ('livianos', 'Livianos'), ('medianos', 'Medianos'), ('pesados', 'Pesados'), ('especiales', 'Especiales')], default='', help_text='Solo con nombre_cliente completado: en qué categoría de peso (Menores/Livianos/.../Especiales) mostrar esta unidad virtual al cliente. Vacío = usa la misma categoría de peso que la categoría real de base.', max_length=20),
        ),
    ]
