# Generated by Django 6.0.8 on 2026-08-15 00:51

from django.db import migrations, models
from django.utils import timezone
import json


def migrate_request_boundary_forward(apps, schema_editor):
    """Read request_boundary_at from state_data JSON, copy to column, remove from JSON."""
    BotConversationState = apps.get_model('whatsapp_bot_v4', 'BotConversationState')

    for record in BotConversationState.objects.all():
        state_data = record.state_data or {}
        boundary_str = state_data.pop('request_boundary_at', None)

        if boundary_str:
            try:
                # Parse ISO string to datetime
                if isinstance(boundary_str, str):
                    record.request_boundary_at = timezone.datetime.fromisoformat(boundary_str)
                    record.state_data = state_data
                    record.save(update_fields=['request_boundary_at', 'state_data'])
            except (ValueError, TypeError):
                pass


def migrate_request_boundary_reverse(apps, schema_editor):
    """Reversal: move request_boundary_at from column back to state_data JSON."""
    BotConversationState = apps.get_model('whatsapp_bot_v4', 'BotConversationState')

    for record in BotConversationState.objects.all():
        if record.request_boundary_at:
            state_data = record.state_data or {}
            state_data['request_boundary_at'] = record.request_boundary_at.isoformat()
            record.state_data = state_data
            record.save(update_fields=['state_data'])


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot_v4', '0003_quote_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversationstate',
            name='request_boundary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_request_boundary_forward, migrate_request_boundary_reverse),
    ]
