# Generated by Django 6.0.8 on 2026-08-18 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_request_lifecycle_observability'),
        ('whatsapp_bot_v4', '0004_move_request_boundary_to_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('bot', 'Bot'), ('advisor', 'Advisor'), ('hybrid', 'Both (advisor priority)')], default='bot', max_length=10)),
                ('control_mode', models.CharField(choices=[('manual', 'Manual via CRM buttons'), ('automatic', 'Auto-detect advisor activity')], default='manual', max_length=10)),
                ('last_human_message_at', models.DateTimeField(blank=True, null=True)),
                ('auto_return_to_bot_after_minutes', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='whatsapp.conversacionwhatsapp')),
            ],
            options={
                'unique_together': {('conversation',)},
            },
        ),
    ]
