# Generated by Django 6.0.8 on 2026-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot_v4', '0005_conversationownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversationstate',
            name='reservation_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='botconversationstate',
            name='status',
            field=models.CharField(choices=[('collecting', 'Recolectando datos'), ('ready_to_quote', 'Lista para cotizar'), ('quoted', 'Cotizada'), ('pending_human_quote', 'Pendiente de cotización humana'), ('reservation', 'Reservando servicio')], default='collecting', max_length=24),
        ),
    ]
