# Generated by Django 6.0.8 on 2026-08-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot_v4', '0006_add_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('meta', 'Meta Graph API'), ('ycloud', 'YCloud')], max_length=10)),
                ('external_message_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-processed_at'],
                'unique_together': {('source', 'external_message_id')},
            },
        ),
    ]
