# Generated by Django 6.0.8 on 2026-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot_v4', '0007_add_webhook_event_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bot Global Config',
            },
        ),
    ]
