# Generated by Django 6.0.8 on 2026-08-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot_v4', '0008_botglobalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='discard_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='discard_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
