# Generated by Django 6.0.6 on 2026-08-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot_v4', '0009_add_webhook_discard_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='botglobalconfig',
            name='transportistas_paused',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botglobalconfig',
            name='transportistas_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
