# Generated by Django 6.0.6 on 2026-09-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot_v4', '0010_botglobalconfig_transportistas_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botglobalconfig',
            name='operativo_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botglobalconfig',
            name='operativo_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
