# Generated by Django 6.0.6 on 2026-09-10 23:13

import apps.encomiendas.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tercerizacion', '0011_transportista_pago_banco_transportista_pago_cci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('distritos', models.JSONField(default=list, help_text='Lista de distritos, en minúsculas.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Zona de reparto',
                'verbose_name_plural': 'Zonas de reparto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=16, unique=True)),
                ('token', models.CharField(default=apps.encomiendas.models._token, editable=False, max_length=32, unique=True)),
                ('nivel', models.CharField(choices=[('express', 'Express (mismo día)'), ('standard', 'Standard (día siguiente)')], default='express', max_length=10)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('asignado', 'Asignado'), ('recogido', 'Recogido'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('fallido', 'No entregado'), ('devuelto', 'Devuelto al remitente'), ('cancelado', 'Cancelado')], db_index=True, default='registrado', max_length=12)),
                ('remitente_nombre', models.CharField(max_length=160)),
                ('remitente_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('origen_distrito', models.CharField(max_length=120)),
                ('origen_direccion', models.CharField(max_length=255)),
                ('origen_referencia', models.CharField(blank=True, default='', max_length=255)),
                ('destinatario_nombre', models.CharField(max_length=160)),
                ('destinatario_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('destino_distrito', models.CharField(max_length=120)),
                ('destino_direccion', models.CharField(max_length=255)),
                ('destino_referencia', models.CharField(blank=True, default='', max_length=255)),
                ('contenido', models.CharField(blank=True, default='', max_length=255)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('largo_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('ancho_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('alto_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_contraentrega', models.BooleanField(default=False)),
                ('monto_contraentrega', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recogido_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('recibido_por', models.CharField(blank=True, default='', max_length=160)),
                ('prueba_foto', models.CharField(blank=True, default='', max_length=255)),
                ('motivo_fallo', models.CharField(blank=True, default='', max_length=200)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='tercerizacion.transportista')),
                ('transportista_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='tercerizacion.transportistavehiculo')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('asignado', 'Asignado'), ('recogido', 'Recogido'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('fallido', 'No entregado'), ('devuelto', 'Devuelto al remitente'), ('cancelado', 'Cancelado')], max_length=12)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='encomiendas.envio')),
            ],
            options={
                'verbose_name': 'Evento de seguimiento',
                'verbose_name_plural': 'Eventos de seguimiento',
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TarifaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('express', 'Express (mismo día)'), ('standard', 'Standard (día siguiente)')], default='express', max_length=10)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('incluye_kg', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('precio_kg_extra', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eta_horas', models.PositiveSmallIntegerField(default=6, help_text='Estimado de entrega, en horas.')),
                ('activo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_hasta', to='encomiendas.zonareparto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_desde', to='encomiendas.zonareparto')),
            ],
            options={
                'verbose_name': 'Tarifa de zona',
                'verbose_name_plural': 'Tarifas de zona',
                'constraints': [models.UniqueConstraint(fields=('origen', 'destino', 'nivel'), name='tarifa_zona_unica')],
            },
        ),
    ]
