# Generated by Django 6.0.6 on 2026-09-10 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0001_initial'),
        ('tercerizacion', '0011_transportista_pago_banco_transportista_pago_cci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='intentos_entrega',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envio',
            name='orden_ruta',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envio',
            name='prueba_firma',
            field=models.TextField(blank=True, default='', help_text='Firma capturada (data URL).'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='prueba_foto',
            field=models.FileField(blank=True, null=True, upload_to='encomiendas/pod/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='RutaReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=16, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada')], default='planificada', max_length=12)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_reparto', to='tercerizacion.transportista')),
                ('transportista_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tercerizacion.transportistavehiculo')),
            ],
            options={
                'verbose_name': 'Ruta de reparto',
                'verbose_name_plural': 'Rutas de reparto',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas', to='encomiendas.rutareparto'),
        ),
    ]
