# Generated by Django 6.0.6 on 2026-09-10 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0002_envio_intentos_entrega_envio_orden_ruta_and_more'),
        ('tercerizacion', '0011_transportista_pago_banco_transportista_pago_cci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEncomiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_cod_porcentaje', models.DecimalField(decimal_places=2, default=3, help_text='Comisión de la plataforma sobre lo cobrado contra-entrega, en %.', max_digits=5)),
                ('envio_incluido_en_cod', models.BooleanField(default=True, help_text='Si está activo, el monto contra-entrega incluye el precio del envío (la plataforma lo retiene). Si no, el envío se cobra aparte.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de encomiendas',
                'verbose_name_plural': 'Configuración de encomiendas',
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_a_remitir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_cobrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_comprobante',
            field=models.FileField(blank=True, null=True, upload_to='encomiendas/cod/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_medio',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape / Plin'), ('tarjeta', 'Tarjeta')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_remitido',
            field=models.BooleanField(default=False, help_text='La plataforma le pagó al remitente su parte.'),
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_remitido_ref',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_rendido',
            field=models.BooleanField(default=False, help_text='El motorizado entregó esta plata a la plataforma.'),
        ),
        migrations.CreateModel(
            name='RendicionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=16, unique=True)),
                ('esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entregado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conciliada', 'Conciliada')], default='pendiente', max_length=12)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conciliada_en', models.DateTimeField(blank=True, null=True)),
                ('conciliada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones_caja', to='tercerizacion.transportista')),
            ],
            options={
                'verbose_name': 'Rendición de caja',
                'verbose_name_plural': 'Rendiciones de caja',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='rendicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='encomiendas.rendicioncaja'),
        ),
    ]
