# Generated by Django 6.0.6 on 2026-09-11 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0003_configuracionencomiendas_envio_cod_a_remitir_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='external_ref',
            field=models.CharField(blank=True, default='', help_text='ID del pedido en el sistema del socio.', max_length=120),
        ),
        migrations.AddField(
            model_name='envio',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='partners.sociocomercial'),
        ),
    ]
