# Generated by Django 6.0.6 on 2026-09-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0004_envio_external_ref_envio_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='punto_entrega_destino',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('asignado', 'Asignado'), ('recogido', 'Recogido'), ('en_ruta', 'En ruta'), ('en_destino', 'Llegó a destino (punto de entrega)'), ('entregado', 'Entregado'), ('fallido', 'No entregado'), ('devuelto', 'Devuelto al remitente'), ('cancelado', 'Cancelado')], db_index=True, default='registrado', max_length=12),
        ),
        migrations.AlterField(
            model_name='envio',
            name='nivel',
            field=models.CharField(choices=[('express', 'Express (mismo día)'), ('standard', 'Standard (día siguiente)'), ('interprovincial', 'Interprovincial (a otra ciudad)')], default='express', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventotracking',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('asignado', 'Asignado'), ('recogido', 'Recogido'), ('en_ruta', 'En ruta'), ('en_destino', 'Llegó a destino (punto de entrega)'), ('entregado', 'Entregado'), ('fallido', 'No entregado'), ('devuelto', 'Devuelto al remitente'), ('cancelado', 'Cancelado')], max_length=12),
        ),
    ]
