# Generated by Django 6.0.6 on 2026-09-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0005_envio_punto_entrega_destino_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoEntregaDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(db_index=True, help_text="Ej. 'Arequipa'. Case-insensitive al buscar.", max_length=120)),
                ('nombre', models.CharField(help_text="Ej. 'Agencia Arequipa Centro'.", max_length=160)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('horario', models.CharField(blank=True, default='', help_text="Ej. 'Lun-Sáb 9am-7pm'.", max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Punto de entrega en destino',
                'verbose_name_plural': 'Puntos de entrega en destino',
                'ordering': ['ciudad', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='destino_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='destino_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
