# Generated by Django 6.0.6 on 2026-09-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0006_puntoentregadestino_envio_destino_lat_and_more'),
        ('tercerizacion', '0013_transportista_direccion_transportista_lat_frecuente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='transportista_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_reparto_destino', to='tercerizacion.transportista'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('asignado', 'Asignado'), ('recogido', 'Recogido'), ('en_ruta', 'En ruta'), ('en_destino', 'Llegó a destino (punto de entrega)'), ('en_reparto_destino', 'En reparto a domicilio (destino)'), ('entregado', 'Entregado'), ('fallido', 'No entregado'), ('devuelto', 'Devuelto al remitente'), ('cancelado', 'Cancelado')], db_index=True, default='registrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventotracking',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('asignado', 'Asignado'), ('recogido', 'Recogido'), ('en_ruta', 'En ruta'), ('en_destino', 'Llegó a destino (punto de entrega)'), ('en_reparto_destino', 'En reparto a domicilio (destino)'), ('entregado', 'Entregado'), ('fallido', 'No entregado'), ('devuelto', 'Devuelto al remitente'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
