# Generated by Django 6.0.6 on 2026-09-21 16:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0007_envio_transportista_destino_alter_envio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionencomiendas',
            name='costo_entrega_domicilio_nacional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Entrega en el domicilio de destino (otra ciudad) para un envío nacional — suele ser más barato que el recojo en Lima (menos tráfico, distancias más cortas).', max_digits=8),
        ),
        migrations.AddField(
            model_name='configuracionencomiendas',
            name='costo_recojo_domicilio_nacional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recojo en el domicilio de origen (Lima) para un envío nacional.', max_digits=8),
        ),
    ]
