# Generated by Django 6.0.6 on 2026-09-10 17:23

import apps.pagos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0015_alter_pagoreserva_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(default='parcial', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('email_pagador', models.EmailField(blank=True, default='', max_length=254)),
                ('pasarela', models.CharField(default='fake', max_length=20)),
                ('token', models.CharField(default=apps.pagos.models._token, editable=False, max_length=64, unique=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('procesando', 'Procesando'), ('pagada', 'Pagada'), ('fallida', 'Fallida'), ('expirada', 'Expirada'), ('reembolsada', 'Reembolsada')], default='creada', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('detalle_error', models.CharField(blank=True, default='', max_length=300)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('origen', models.CharField(default='link', max_length=16)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago', to='servicios.cuotaservicio')),
                ('pago_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_pago', to='servicios.pagoreserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pago', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Orden de pago',
                'verbose_name_plural': 'Órdenes de pago',
                'ordering': ['-creado_en'],
            },
        ),
    ]
