# Generated by Django 6.0.6 on 2026-06-10 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('leads', '0012_lead_whatsapp_channel'),
        ('whatsapp', '0007_whatsappchannel_botschedule_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('en_ruta', 'En ruta'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('tipo_servicio', models.CharField(blank=True, max_length=80)),
                ('distrito_origen', models.CharField(blank=True, max_length=120)),
                ('distrito_destino', models.CharField(blank=True, max_length=120)),
                ('direccion_origen', models.CharField(blank=True, max_length=255)),
                ('direccion_destino', models.CharField(blank=True, max_length=255)),
                ('piso_origen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('piso_destino', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acceso_origen', models.CharField(blank=True, max_length=120)),
                ('acceso_destino', models.CharField(blank=True, max_length=120)),
                ('lista_objetos', models.TextField(blank=True)),
                ('objetos_pesados', models.TextField(blank=True)),
                ('incluye_personal_carga', models.BooleanField(blank=True, null=True)),
                ('requiere_desarmado', models.BooleanField(blank=True, null=True)),
                ('peso_carga_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen_carga_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('horario_servicio', models.CharField(blank=True, max_length=80)),
                ('precio_cotizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dni_ruc', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('nota_interna', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asesorados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='clientes.cliente')),
                ('lead_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_generado', to='leads.lead')),
                ('whatsapp_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='whatsapp.whatsappchannel')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
