# Generated by Django 6.0.6 on 2026-06-12 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_atendido_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='acceso_destino_opciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicio',
            name='acceso_origen_opciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicio',
            name='detalle_carga',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='requisitos_especiales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_comprobante',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('boleta', 'Boleta'), ('factura', 'Factura')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_embalaje',
            field=models.CharField(choices=[('sin_embalaje', 'Sin embalaje'), ('basico', 'Embalaje básico'), ('muebles', 'Embalaje de muebles y artefactos'), ('full', 'Embalaje full')], default='sin_embalaje', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='direccion_destino',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='direccion_origen',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('asignado', 'Asignado'), ('en_ruta', 'En ruta'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='horario_servicio',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='piso_destino',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='piso_origen',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
