# Generated by Django 6.0.6 on 2026-06-12 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('adelanto', 'Adelanto'), ('parcial', 'Pago parcial'), ('final', 'Pago final'), ('descuento', 'Descuento'), ('ajuste', 'Ajuste')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('yape', 'Yape'), ('plin', 'Plin'), ('bcp_personal', 'BCP Persona Natural'), ('bcp_sos', 'BCP SOS Empresa'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='servicios.servicio')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de reserva',
                'verbose_name_plural': 'Pagos de reservas',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
