# Generated by Django 6.0.6 on 2026-08-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_pagoreserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cantidad_operarios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='requiere_armado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServicioUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('origen', 'Origen'), ('parada', 'Parada'), ('destino', 'Destino')], max_length=12)),
                ('distrito', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('piso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ascensor', models.BooleanField(blank=True, null=True)),
                ('acceso_camion', models.BooleanField(blank=True, null=True)),
                ('distancia_acarreo', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones_acceso', models.TextField(blank=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='servicios.servicio')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['servicio', 'tipo', 'orden'], name='servicios_s_servici_f0b786_idx')],
                'constraints': [models.UniqueConstraint(fields=('servicio', 'orden'), name='servicio_ubicacion_orden_unico'), models.UniqueConstraint(condition=models.Q(('tipo__in', ['origen', 'destino'])), fields=('servicio', 'tipo'), name='servicio_ubicacion_extremo_unico')],
            },
        ),
    ]
