# Generated by Django 6.0.6 on 2026-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_ordered_locations_and_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='autoriza_compartir_fotos_transportistas',
            field=models.BooleanField(default=False, help_text='El cliente autorizó compartir las fotos de esta mudanza con el transportista que la ejecute. Una autorización por servicio, confirmada por el asesor antes de reenviar cualquier foto.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='es_tercerizada',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
