# Generated by Django 6.0.6 on 2026-08-30 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_es_transportista'),
        ('servicios', '0006_servicio_autoriza_compartir_fotos_transportistas_and_more'),
        ('tercerizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='oferta_ganadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tercerizacion.ofertatransportista'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='transportista_asignado',
            field=models.ForeignKey(blank=True, help_text='Cliente (con es_transportista=True) al que se adjudicó esta carga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_como_transportista', to='clientes.cliente'),
        ),
    ]
