# Generated by Django 6.0.6 on 2026-09-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_servicio_oferta_ganadora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='es_interprovincial',
            field=models.BooleanField(default=False, help_text='Ruta fuera de Lima Metropolitana. Heredado del lead de origen.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_confirmacion',
            field=models.DateField(blank=True, help_text='Fecha en que la venta se confirmó (se creó la reserva desde un lead aceptado).', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha en que el servicio se marcó como finalizado.', null=True),
        ),
    ]
