# Generated by Django 6.0.6 on 2026-09-07 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_servicio_es_interprovincial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionOperaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventana_nocturna_inicio', models.TimeField(default=datetime.time(17, 0))),
                ('ventana_nocturna_fin', models.TimeField(default=datetime.time(7, 0))),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de operaciones',
                'verbose_name_plural': 'Configuración de operaciones',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='modalidad_ejecucion',
            field=models.CharField(choices=[('propio', 'Nuestro equipo'), ('tercerizado', 'Transportistas')], db_index=True, default='propio', max_length=12),
        ),
    ]
