# Generated by Django 6.0.6 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_configuracionoperaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='modalidad_ejecucion',
            field=models.CharField(choices=[('por_definir', 'Por definir'), ('propio', 'Nuestro equipo'), ('tercerizado', 'Transportistas')], db_index=True, default='propio', max_length=12),
        ),
    ]
