# Generated by Django 6.0.6 on 2026-09-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_alter_servicio_modalidad_ejecucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='derivar_interprovincial_auto',
            field=models.BooleanField(default=False, help_text='Si está activo, las cargas interprovinciales se publican solas a los transportistas (modo de precio abierto) en cuanto tienen los datos completos, sin que el asesor las cotice.'),
        ),
    ]
