# Generated by Django 6.0.6 on 2026-09-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_configuracionoperaciones_derivar_interprovincial_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='markup_tercerizacion_porcentaje',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Recargo sobre el costo del transportista para fijar el precio al cliente cuando una carga tercerizada no tiene cotización propia (p.ej. 25 = costo + 25 %). Es la rentabilidad objetivo de la plataforma en tercerización.', max_digits=5),
        ),
    ]
