# Generated by Django 6.0.6 on 2026-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_configuracionoperaciones_markup_tercerizacion_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='monto_minimo_comisionable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Los servicios tercerizados por debajo de este monto no pagan comisión a la plataforma. 0 = todos comisionan.', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicio',
            name='sin_comision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='sin_comision_motivo',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
