# Generated by Django 6.0.6 on 2026-09-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_configuracionoperaciones_monto_minimo_comisionable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='adelanto_pct_default',
            field=models.DecimalField(decimal_places=2, default=30, help_text="% de adelanto del esquema 'adelanto + saldo'.", max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='esquema_cobro_default',
            field=models.CharField(default='adelanto_saldo', help_text='Plan de cuotas que se aplica a una reserva nueva (el asesor lo puede cambiar por servicio).', max_length=32),
        ),
        migrations.CreateModel(
            name='CuotaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('disparador', models.CharField(choices=[('reserva', 'Al reservar'), ('origen', 'En el origen'), ('destino', 'En el destino'), ('dias', 'A X días del servicio'), ('fecha', 'Fecha fija')], default='reserva', max_length=10)),
                ('dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('base', models.CharField(choices=[('porcentaje', '% del total'), ('monto', 'Monto fijo')], default='porcentaje', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Cuota de cobro',
                'verbose_name_plural': 'Plan de cobro',
                'ordering': ['servicio', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='pagoreserva',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='servicios.cuotaservicio'),
        ),
        migrations.AddConstraint(
            model_name='cuotaservicio',
            constraint=models.UniqueConstraint(fields=('servicio', 'orden'), name='cuota_servicio_orden_unico'),
        ),
    ]
