# Generated by Django 6.0.6 on 2026-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_configuracionoperaciones_adelanto_pct_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoreserva',
            name='metodo_pago',
            field=models.CharField(choices=[('yape', 'Yape'), ('plin', 'Plin'), ('bcp_personal', 'BCP Persona Natural'), ('bcp_sos', 'BCP SOS Empresa'), ('tarjeta', 'Tarjeta / pasarela'), ('otro', 'Otro')], max_length=20),
        ),
    ]
