# Generated by Django 6.0.6 on 2026-09-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_alter_pagoreserva_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='derivar_al_rechazar_precio',
            field=models.BooleanField(default=False, help_text='Si el cliente rechaza el precio de una carga nacional, se publica sola a los transportistas para que oferten (en vez de abrir una negociación con el asesor).'),
        ),
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='derivar_fuera_horario',
            field=models.BooleanField(default=False, help_text='Fuera del horario de atención, las cargas nacionales con datos completos se publican solas a los transportistas (el asesor no está).'),
        ),
    ]
