# Generated by Django 6.0.6 on 2026-09-11 16:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_configuracionoperaciones_derivar_al_rechazar_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='lat_referencia_local',
            field=models.DecimalField(decimal_places=6, default=Decimal('-12.046374'), help_text="Latitud del punto de referencia para medir si una carga es 'local' (Lima Cercado por defecto).", max_digits=9),
        ),
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='lng_referencia_local',
            field=models.DecimalField(decimal_places=6, default=Decimal('-77.042793'), help_text="Longitud del punto de referencia para medir si una carga es 'local'.", max_digits=9),
        ),
        migrations.AddField(
            model_name='configuracionoperaciones',
            name='radio_local_km',
            field=models.DecimalField(decimal_places=1, default=Decimal('60'), help_text='Si el origen o el destino de la carga están a más de esta distancia (km, línea recta) del punto de referencia, la carga se clasifica como nacional/interprovincial. Solo aplica cuando hay coordenadas capturadas (autocompletado de dirección); si no hay coordenadas, se mantiene la detección por distrito/texto.', max_digits=6),
        ),
    ]
