# Generated by Django 6.0.6 on 2026-09-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_configuracionoperaciones_lat_referencia_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='modo_carga',
            field=models.CharField(choices=[('completa', 'Completa (camión dedicado)'), ('parcial', 'Parcial (consolidada con otra carga del transportista)')], default='completa', help_text='Solo relevante si es_interprovincial=True. Heredado del lead de origen (Express/camión dedicado vs. Consolidada/comparte camión).', max_length=10),
        ),
    ]
