# Generated by Django 6.0.6 on 2026-09-09 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0017_lead_categoria_carga_lead_codigo_and_more'),
        ('servicios', '0010_alter_servicio_modalidad_ejecucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_tipo', models.CharField(db_index=True, max_length=16)),
                ('capacidad', models.CharField(db_index=True, max_length=64)),
                ('efecto', models.CharField(max_length=24)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField()),
                ('codigo_error', models.CharField(blank=True, max_length=32)),
                ('error', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.lead')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='servicios.servicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción del agente',
                'verbose_name_plural': 'Acciones del agente',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['capacidad', '-creado_en'], name='agente_acci_capacid_cac4e9_idx'), models.Index(fields=['ok', '-creado_en'], name='agente_acci_ok_2a967b_idx')],
            },
        ),
    ]
