# Generated by Django 6.0.6 on 2026-09-10 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_tipo', models.CharField(db_index=True, max_length=16)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('cerrada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación con el agente',
                'verbose_name_plural': 'Conversaciones con el agente',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='TurnoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('agente', 'Agente'), ('sistema', 'Sistema')], max_length=10)),
                ('contenido', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('iteraciones', models.PositiveSmallIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_out', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agente.conversacionagente')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(db_index=True, max_length=64)),
                ('efecto', models.CharField(max_length=24)),
                ('args', models.JSONField(default=dict)),
                ('resumen', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicada', 'Aplicada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], db_index=True, default='pendiente', max_length=12)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=200)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('accion_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agente.accionagente')),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas', to='agente.conversacionagente')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Quién la ve / la confirma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta del agente',
                'verbose_name_plural': 'Propuestas del agente',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='agente_prop_usuario_0117ac_idx')],
            },
        ),
    ]
