# Generated by Django 6.0.6 on 2026-09-10 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0002_conversacionagente_turnoagente_propuestaaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('categoria', models.CharField(choices=[('empresa', 'Empresa'), ('servicios', 'Servicios'), ('logistica', 'Logística / operación'), ('precios', 'Precios / cotización'), ('politicas', 'Políticas'), ('procedimientos', 'Procedimientos'), ('glosario', 'Glosario del rubro')], db_index=True, max_length=20)),
                ('contenido', models.TextField(help_text='Markdown.')),
                ('visibilidad', models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno')], default='interno', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de conocimiento',
                'verbose_name_plural': 'Conocimiento del agente',
                'ordering': ['categoria', 'titulo'],
            },
        ),
    ]
