# Generated by Django 6.0.6 on 2026-06-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('capacidad_toneladas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Ayudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ayudantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ayudante',
                'verbose_name_plural': 'Ayudantes',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='EquipoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ayudantes', models.ManyToManyField(blank=True, related_name='equipos_dia', to='campo.ayudante')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_dia', to='campo.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_dia', to='campo.vehiculo')),
            ],
            options={
                'verbose_name': 'Equipo del día',
                'verbose_name_plural': 'Equipos del día',
                'unique_together': {('fecha', 'vehiculo')},
            },
        ),
        migrations.CreateModel(
            name='ProgramacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_operativo', models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En ruta'), ('en_servicio', 'En servicio'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('ayudantes', models.ManyToManyField(blank=True, related_name='programaciones', to='campo.ayudante')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='campo.conductor')),
                ('equipo_dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='campo.equipodia')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='servicios.servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='campo.vehiculo')),
            ],
            options={
                'verbose_name': 'Programación de servicio',
                'verbose_name_plural': 'Programaciones de servicios',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
