# Generated by Django 6.0.6 on 2026-06-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='categoria_licencia',
            field=models.CharField(blank=True, choices=[('A-I', 'A-I'), ('A-II-a', 'A-II-a'), ('A-II-b', 'A-II-b'), ('A-III-a', 'A-III-a'), ('A-III-b', 'A-III-b'), ('A-III-c', 'A-III-c'), ('B-I', 'B-I'), ('B-II-a', 'B-II-a'), ('B-II-b', 'B-II-b'), ('B-II-c', 'B-II-c')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Licencia'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=40, verbose_name='N° Licencia'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidad (m³)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_extintor',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Extintor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_rtv',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento RTV'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_soat',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento SOAT'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad_toneladas',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Capacidad (t)'),
        ),
    ]
