# Generated by Django 6.0.6 on 2026-06-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0003_alter_equipodia_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipodia',
            name='conductores_ayudantes',
            field=models.ManyToManyField(blank=True, related_name='equipos_como_ayudante', to='campo.conductor'),
        ),
    ]
