# Generated by Django 6.0.6 on 2026-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0005_equipofrecuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionservicio',
            name='origen_asignacion',
            field=models.CharField(choices=[('manual', 'Asignado por un asesor'), ('auto', 'Asignación automática')], default='manual', max_length=10),
        ),
    ]
