# Generated by Django 6.0.6 on 2026-09-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0006_programacionservicio_origen_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionservicio',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='campo.conductor'),
        ),
    ]
