# Generated by Django 6.0.6 on 2026-09-09 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0007_alter_programacionservicio_conductor'),
        ('servicios', '0009_configuracionoperaciones_and_more'),
        ('tercerizacion', '0004_transportista_transportistavehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaPizarraTransportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('conductor_externo', models.CharField(blank=True, max_length=160)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fila de transportista en la pizarra',
                'verbose_name_plural': 'Filas de transportistas en la pizarra',
            },
        ),
        migrations.AddField(
            model_name='programacionservicio',
            name='conductor_externo',
            field=models.CharField(blank=True, max_length=160, verbose_name='Conductor del transportista'),
        ),
        migrations.AddField(
            model_name='programacionservicio',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='tercerizacion.transportista'),
        ),
        migrations.AddField(
            model_name='programacionservicio',
            name='transportista_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='tercerizacion.transportistavehiculo'),
        ),
        migrations.AlterField(
            model_name='programacionservicio',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='campo.vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='programacionservicio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transportista_vehiculo__isnull', True), ('vehiculo__isnull', False)), models.Q(('transportista_vehiculo__isnull', False), ('vehiculo__isnull', True)), _connector='OR'), name='prog_vehiculo_xor_transportista'),
        ),
        migrations.AddField(
            model_name='filapizarratransportista',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filapizarratransportista',
            name='transportista_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filas_pizarra', to='tercerizacion.transportistavehiculo'),
        ),
        migrations.AddConstraint(
            model_name='filapizarratransportista',
            constraint=models.UniqueConstraint(fields=('fecha', 'transportista_vehiculo'), name='fila_pizarra_unica_por_fecha_vehiculo'),
        ),
    ]
