# Generated by Django 6.0.6 on 2026-06-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_recomendado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios_similares_encontrados', models.PositiveIntegerField(default=0)),
                ('explicacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='leads.lead')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ServicioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_servicio', models.CharField(max_length=80)),
                ('distrito_origen', models.CharField(max_length=120)),
                ('distrito_destino', models.CharField(max_length=120)),
                ('piso_origen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('piso_destino', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ascensor_origen', models.BooleanField(default=False)),
                ('ascensor_destino', models.BooleanField(default=False)),
                ('lista_objetos', models.TextField(blank=True)),
                ('camion_usado', models.CharField(blank=True, max_length=120)),
                ('ayudantes', models.PositiveSmallIntegerField(default=2)),
                ('precio_cotizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo_servicio', 'distrito_origen', 'distrito_destino'], name='cotizador_s_tipo_se_1849b2_idx')],
            },
        ),
    ]
