# Generated by Django 6.0.6 on 2026-06-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciohistorico',
            name='acceso_destino',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='acceso_origen',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='capacidad_camion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='distancia_carga_destino_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='distancia_carga_origen_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='modalidad_servicio',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='objetos_pesados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='peso_carga_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='requiere_desarmado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='volumen_carga_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
