# Generated by Django 6.0.6 on 2026-06-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_serviciohistorico_acceso_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciohistorico',
            name='camion_llega_destino',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='camion_llega_origen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
