# Generated by Django 6.0.6 on 2026-06-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_serviciohistorico_camion_llega_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciohistorico',
            name='fuente',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='serviciohistorico',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='serviciohistorico',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_externa', ''), _negated=True), fields=('fuente', 'referencia_externa'), name='historico_fuente_referencia_unica'),
        ),
    ]
