# Generated by Django 6.0.6 on 2026-06-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_serviciohistorico_fuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciohistorico',
            name='ascensor_destino',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviciohistorico',
            name='ascensor_origen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
