# Generated by Django 6.0.6 on 2026-06-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_alter_serviciohistorico_ascensor_destino_and_more'),
        ('leads', '0012_lead_whatsapp_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciohistorico',
            name='lead_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_generados', to='leads.lead'),
        ),
        migrations.AddConstraint(
            model_name='serviciohistorico',
            constraint=models.UniqueConstraint(condition=models.Q(('lead_origen', None), _negated=True), fields=('lead_origen',), name='historico_lead_origen_unico'),
        ),
    ]
