# Generated by Django 6.0.6 on 2026-08-07 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_add_lead_origen_servicio_historico'),
        ('leads', '0012_lead_whatsapp_channel'),
        ('whatsapp', '0008_add_modo_to_botschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('origen', models.CharField(choices=[('bot', 'Bot'), ('asesor', 'Asesor')], max_length=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('en_negociacion', 'En negociacion'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_comerciales', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_comerciales', to='whatsapp.whatsappchannel')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_comerciales', to='leads.lead')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='RevisionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('snapshot_servicio', models.JSONField(default=dict)),
                ('precio_sugerido_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_sugerido_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margen_minimo_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condiciones', models.TextField(blank=True)),
                ('vigencia_dias', models.PositiveSmallIntegerField(default=7)),
                ('observacion_interna', models.TextField(blank=True)),
                ('mensaje_whatsapp', models.TextField(blank=True)),
                ('enviada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='cotizador.cotizacioncomercial')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_cotizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='EnvioCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_message_id', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leido'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('intento', models.PositiveSmallIntegerField(default=1)),
                ('error_codigo', models.CharField(blank=True, max_length=80)),
                ('error_detalle', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_cotizacion', to='whatsapp.whatsappchannel')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='cotizador.revisioncotizacion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('terminada', 'Terminada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('datos_faltantes', models.JSONField(blank=True, default=list)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cotizacion_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prioridad', 'creada_en'],
            },
        ),
    ]
