# Generated by Django 6.0.6 on 2026-08-07 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_cotizacioncomercial_revisioncotizacion_and_more'),
        ('leads', '0012_lead_whatsapp_channel'),
        ('whatsapp', '0009_conversacionwhatsapp_auditoriawhatsapp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='conversacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cotizacion', to='whatsapp.conversacionwhatsapp'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cotizacion_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cotizacion', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='cotizacioncomercial',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='cotizador.solicitudcotizacion'),
        ),
        migrations.AddConstraint(
            model_name='revisioncotizacion',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'numero'), name='cotizador_revision_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='revisioncotizacion',
            constraint=models.CheckConstraint(condition=models.Q(('precio_final__gt', 0)), name='cotizador_revision_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='enviocotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('meta_message_id', ''), _negated=True), fields=('meta_message_id',), name='cotizador_envio_meta_id_unico'),
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacion',
            index=models.Index(fields=['estado', 'prioridad', 'creada_en'], name='cotizador_s_estado_49bbad_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudcotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'en_proceso'])), fields=('lead',), name='cotizador_solicitud_activa_unica_por_lead'),
        ),
        migrations.AddIndex(
            model_name='cotizacioncomercial',
            index=models.Index(fields=['estado', '-creada_en'], name='cotizador_c_estado_dc1769_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacioncomercial',
            index=models.Index(fields=['channel', '-creada_en'], name='cotizador_c_channel_e36e8f_idx'),
        ),
    ]
