# Generated by Django 6.0.6 on 2026-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_solicitudcotizacion_conversacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocotizacion',
            name='leido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviocotizacion',
            name='max_intentos',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='enviocotizacion',
            name='proximo_reintento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
