# Generated by Django 6.0.6 on 2026-08-09 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_enviocotizacion_leido_en_and_more'),
        ('integrations', '0003_external_message_local_identity'),
        ('leads', '0012_lead_whatsapp_channel'),
        ('whatsapp', '0011_configuracionbot_asesor_predeterminado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomercial',
            name='moneda',
            field=models.CharField(default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='enviocotizacion',
            name='outbox_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envio_cotizacion', to='integrations.integrationoutboxevent'),
        ),
        migrations.AddField(
            model_name='revisioncotizacion',
            name='cotizacion_tecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_comerciales', to='cotizador.cotizacion'),
        ),
        migrations.AddField(
            model_name='revisioncotizacion',
            name='source_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='cotizacioncomercial',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'borrador'), ('solicitud__isnull', False)), fields=('solicitud',), name='cotizador_borrador_unico_solicitud'),
        ),
        migrations.AddConstraint(
            model_name='revisioncotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('source_key',), name='cotizador_revision_source_key_unica'),
        ),
    ]
