# Generated by Django 6.0.6 on 2026-09-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0010_stage9_commercial_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='tipo',
            field=models.CharField(choices=[('revision', 'Revisión'), ('cotizacion', 'Cotización')], db_index=True, default='cotizacion', max_length=20),
        ),
    ]
