# Generated by Django 6.0.6 on 2026-09-07 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0011_solicitudcotizacion_tipo'),
        ('leads', '0016_lead_persona_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=20)),
                ('visto_en', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_pipeline', to='leads.lead')),
                ('visto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['etapa', 'lead'], name='cotizador_p_etapa_6fc4d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('etapa', 'lead'), name='cotizador_pipelinevisto_etapa_lead')],
            },
        ),
    ]
