# Generated by Django 6.0.6 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0012_pipelinevisto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='confianza',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–100. Baja (<40) → el sistema no muestra precio firme; ofrece rango y deriva a asesor/negociación.', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='modo',
            field=models.CharField(choices=[('automatico', 'Automático (motor)'), ('manual', 'Manual (asesor pone precio)')], default='automatico', max_length=12),
        ),
        migrations.AddField(
            model_name='cotizacioncomercial',
            name='precio_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacioncomercial',
            name='precio_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
