# Generated by Django 6.0.6 on 2026-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0013_cotizacion_confianza_cotizacion_modo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='dias_estimados',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tiempo de entrega estimado (días hábiles). Lo usa la carga nacional parcial/consolidada, donde el plazo depende de cuándo el transportista completa su camión. Vacío = no aplica (carga local o completa).', null=True),
        ),
    ]
