# Generated by Django 6.0.6 on 2026-09-21 13:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0014_cotizacion_dias_estimados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_mudanza', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8)),
                ('base_carga', models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=8)),
                ('base_traslado_pequeno', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8)),
                ('base_oficina', models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=8)),
                ('base_corporativo', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8)),
                ('base_otros', models.DecimalField(decimal_places=2, default=Decimal('220.00'), help_text='Tipo de servicio sin base propia arriba.', max_digits=8)),
                ('costo_por_kg', models.DecimalField(decimal_places=2, default=Decimal('0.12'), max_digits=6)),
                ('costo_por_m3', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=8)),
                ('costo_por_piso_sin_ascensor', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Por piso, solo si no hay ascensor.', max_digits=8)),
                ('costo_personal_carga', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('costo_desarmado', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=8)),
                ('costo_objeto_pesado', models.DecimalField(decimal_places=2, default=Decimal('45.00'), help_text='Por cada objeto pesado listado.', max_digits=8)),
                ('costo_camion_no_llega', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Por punto (origen o destino) donde el camión no llega hasta la puerta.', max_digits=8)),
                ('costo_embalaje_basico', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8)),
                ('costo_embalaje_completo', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=8)),
                ('costo_embalaje_full', models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=8)),
                ('costo_descripcion_media', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=8)),
                ('costo_descripcion_grande', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=8)),
                ('costo_descripcion_muy_grande', models.DecimalField(decimal_places=2, default=Decimal('160.00'), max_digits=8)),
                ('costo_caminata_por_bloque', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8)),
                ('rango_min_pct', models.DecimalField(decimal_places=2, default=Decimal('90.00'), help_text='% del precio recomendado — piso del rango.', max_digits=5)),
                ('rango_max_pct', models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='% del precio recomendado — techo del rango.', max_digits=5)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de precios',
                'verbose_name_plural': 'Configuración de precios',
            },
        ),
    ]
