# Generated by Django 6.0.6 on 2026-09-21 13:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0015_configuracionprecios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionprecios',
            name='costo_por_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Por km más allá de km_gratis. 0 = distancia no afecta el precio (comportamiento anterior).', max_digits=8),
        ),
        migrations.AddField(
            model_name='configuracionprecios',
            name='km_gratis',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), help_text='Primeros km sin costo adicional (cubiertos por el precio base).', max_digits=6),
        ),
    ]
