# Generated by Django 6.0.6 on 2026-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjemploConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(default='whatsapp_export', max_length=40)),
                ('referencia_chat', models.CharField(max_length=80)),
                ('turno', models.PositiveIntegerField()),
                ('mensaje_cliente', models.TextField()),
                ('respuesta_negocio', models.TextField()),
                ('etiquetas', models.JSONField(blank=True, default=list)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['referencia_chat', 'turno'],
                'constraints': [models.UniqueConstraint(fields=('fuente', 'referencia_chat', 'turno'), name='ejemplo_conversacion_fuente_chat_turno_unico')],
            },
        ),
    ]
