# Generated by Django 6.0.6 on 2026-08-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        ('leads', '0013_ordered_locations_and_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDeltaAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.PositiveBigIntegerField(db_index=True)),
                ('message_id', models.PositiveBigIntegerField(unique=True)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('state_version', models.CharField(max_length=64)),
                ('mode', models.CharField(default='shadow', max_length=20)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('fallback', 'Fallback')], max_length=20)),
                ('accepted_delta', models.JSONField(blank=True, default=dict)),
                ('legacy_extraction', models.JSONField(blank=True, default=dict)),
                ('rejected_fields', models.JSONField(blank=True, default=list)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('fallback_used', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_delta_audits', to='leads.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='ia_delta_status_idx')],
            },
        ),
    ]
