# Generated by Django 6.0.6 on 2026-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_aideltaaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aideltaaudit',
            name='canonical_state_after',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aideltaaudit',
            name='canonical_state_before',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aideltaaudit',
            name='question_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aideltaaudit',
            name='raw_delta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aideltaaudit',
            name='rejected_delta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
