# Generated by Django 6.0.6 on 2026-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_delta_audit_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_default', models.CharField(blank=True, choices=[('', 'Usar el valor del servidor (.env)'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='', help_text='Proveedor general — aplica a extracción/conversación/copiloto salvo que se anule abajo.', max_length=10)),
                ('proveedor_extraccion', models.CharField(blank=True, choices=[('', 'Usar el valor del servidor (.env)'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='', max_length=10)),
                ('proveedor_conversacion', models.CharField(blank=True, choices=[('', 'Usar el valor del servidor (.env)'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='', max_length=10)),
                ('proveedor_copiloto', models.CharField(blank=True, choices=[('', 'Usar el valor del servidor (.env)'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='', max_length=10)),
                ('modelo_openai', models.CharField(blank=True, default='', help_text='Vacío = usa el modelo por defecto del servidor (OPENAI_MODEL).', max_length=60)),
                ('modelo_deepseek', models.CharField(blank=True, default='', help_text='Vacío = usa el modelo por defecto del servidor (DEEPSEEK_MODEL).', max_length=60)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuración de IA',
            },
        ),
    ]
